"Resource/UI/MainMenuOverride.res"
{
	"MainMenuOverride"
	{
		"CustomizationMenu"
		{
			"MainPanel"
			{
				"SectionContainer"
				{
					"Hitmarkers"
					{
						"Buttons"
						{
							"HitMarkerShape0"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape0"
								"xpos"						"0"
								"ypos"						"0"
								"command"					"engine ih_hitmarker_shape_0"
								"labelText"					"!"
							}
							"HitMarkerShape1"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape1"
								"xpos"						"20"
								"ypos"						"0"
								"command"					"engine ih_hitmarker_shape_1"
								"labelText"					"#"
							}
							"HitMarkerShape2"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape2"
								"xpos"						"40"
								"ypos"						"0"
								"command"					"engine ih_hitmarker_shape_2"
								"labelText"					"$"
							}
							"HitMarkerShape3"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape3"
								"xpos"						"60"
								"ypos"						"0"
								"command"					"engine ih_hitmarker_shape_3"
								"labelText"					"%"
							}
							"HitMarkerShape4"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape4"
								"xpos"						"80"
								"ypos"						"0"
								"command"					"engine ih_hitmarker_shape_4"
								"labelText"					"'"
							}
							"HitMarkerShape5"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape5"
								"xpos"						"100"
								"ypos"						"0"
								"command"					"engine ih_hitmarker_shape_5"
								"labelText"					"("
							}
							"HitMarkerShape6"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape6"
								"xpos"						"120"
								"ypos"						"0"
								"command"					"engine ih_hitmarker_shape_6"
								"labelText"					")"
							}
							"HitMarkerShape7"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape7"
								"xpos"						"140"
								"ypos"						"0"
								"command"					"engine ih_hitmarker_shape_7"
								"labelText"					"*"
							}
							"HitMarkerShape8"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape8"
								"xpos"						"160"
								"ypos"						"0"
								"command"					"engine ih_hitmarker_shape_8"
								"labelText"					"+"
							}
							"HitMarkerShape9"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape9"
								"xpos"						"180"
								"ypos"						"0"
								"command"					"engine ih_hitmarker_shape_9"
								"labelText"					","
							}
							"HitMarkerShape10"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape10"
								"xpos"						"0"
								"ypos"						"20"
								"command"					"engine ih_hitmarker_shape_10"
								"labelText"					"-"
							}
							"HitMarkerShape11"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape11"
								"xpos"						"20"
								"ypos"						"20"
								"command"					"engine ih_hitmarker_shape_11"
								"labelText"					"."
							}
							"HitMarkerShape12"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape12"
								"xpos"						"40"
								"ypos"						"20"
								"command"					"engine ih_hitmarker_shape_12"
								"labelText"					"/"
							}
							"HitMarkerShape13"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape13"
								"xpos"						"60"
								"ypos"						"20"
								"command"					"engine ih_hitmarker_shape_13"
								"labelText"					"0"
							}
							"HitMarkerShape14"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape14"
								"xpos"						"80"
								"ypos"						"20"
								"command"					"engine ih_hitmarker_shape_14"
								"labelText"					"1"
							}
							"HitMarkerShape15"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape15"
								"xpos"						"100"
								"ypos"						"20"
								"command"					"engine ih_hitmarker_shape_15"
								"labelText"					"2"
							}
							"HitMarkerShape16"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape16"
								"xpos"						"120"
								"ypos"						"20"
								"command"					"engine ih_hitmarker_shape_16"
								"labelText"					"3"
							}
							"HitMarkerShape17"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape17"
								"xpos"						"140"
								"ypos"						"20"
								"command"					"engine ih_hitmarker_shape_17"
								"labelText"					"4"
							}
							"HitMarkerShape18"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape18"
								"xpos"						"160"
								"ypos"						"20"
								"command"					"engine ih_hitmarker_shape_18"
								"labelText"					"5"
							}
							"HitMarkerShape19"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape19"
								"xpos"						"180"
								"ypos"						"20"
								"command"					"engine ih_hitmarker_shape_19"
								"labelText"					"6"
							}
							"HitMarkerShape20"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape20"
								"xpos"						"0"
								"ypos"						"40"
								"command"					"engine ih_hitmarker_shape_20"
								"labelText"					"7"
							}
							"HitMarkerShape21"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape21"
								"xpos"						"20"
								"ypos"						"40"
								"command"					"engine ih_hitmarker_shape_21"
								"labelText"					"8"
							}
							"HitMarkerShape22"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape22"
								"xpos"						"40"
								"ypos"						"40"
								"command"					"engine ih_hitmarker_shape_22"
								"labelText"					"9"
							}
							"HitMarkerShape23"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape23"
								"xpos"						"60"
								"ypos"						"40"
								"command"					"engine ih_hitmarker_shape_23"
								"labelText"					":"
							}
							"HitMarkerShape24"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_1"
								"border_armed"				"FLAT_Black_1"
								"defaultFgColor_override"	"TextT4"
								"armedfgcolor_override"		"TextT4"
								"fieldName"					"HitmarkerShape24"
								"xpos"						"80"
								"ypos"						"40"
								"command"					"engine clear; showconsole; echo Disabled temporarily due to a bug."
								"labelText"					";"
							}
							"HitMarkerShape25"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape25"
								"xpos"						"100"
								"ypos"						"40"
								"command"					"engine ih_hitmarker_shape_25"
								"labelText"					"<"
							}
							"HitMarkerShape26"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape26"
								"xpos"						"120"
								"ypos"						"40"
								"command"					"engine ih_hitmarker_shape_26"
								"labelText"					"="
							}
							"HitMarkerShape27"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape27"
								"xpos"						"140"
								"ypos"						"40"
								"command"					"engine ih_hitmarker_shape_27"
								"labelText"					">"
							}
							"HitMarkerShape28"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape28"
								"xpos"						"160"
								"ypos"						"40"
								"command"					"engine ih_hitmarker_shape_28"
								"labelText"					"?"
							}
							"HitMarkerShape29"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape29"
								"xpos"						"180"
								"ypos"						"40"
								"command"					"engine ih_hitmarker_shape_29"
								"labelText"					"@"
							}
							"HitMarkerShape30"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape30"
								"xpos"						"0"
								"ypos"						"60"
								"command"					"engine ih_hitmarker_shape_30"
								"labelText"					"A"
							}
							"HitMarkerShape31"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape31"
								"xpos"						"20"
								"ypos"						"60"
								"command"					"engine ih_hitmarker_shape_31"
								"labelText"					"B"
							}
							"HitMarkerShape32"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape32"
								"xpos"						"40"
								"ypos"						"60"
								"command"					"engine ih_hitmarker_shape_32"
								"labelText"					"C"
							}
							"HitMarkerShape33"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape33"
								"xpos"						"60"
								"ypos"						"60"
								"command"					"engine ih_hitmarker_shape_33"
								"labelText"					"D"
							}
							"HitMarkerShape34"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape34"
								"xpos"						"80"
								"ypos"						"60"
								"command"					"engine ih_hitmarker_shape_34"
								"labelText"					"E"
							}
							"HitMarkerShape35"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape35"
								"xpos"						"100"
								"ypos"						"60"
								"command"					"engine ih_hitmarker_shape_35"
								"labelText"					"F"
							}
							"HitMarkerShape36"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape36"
								"xpos"						"120"
								"ypos"						"60"
								"command"					"engine ih_hitmarker_shape_36"
								"labelText"					"G"
							}
							"HitMarkerShape37"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape37"
								"xpos"						"140"
								"ypos"						"60"
								"command"					"engine ih_hitmarker_shape_37"
								"labelText"					"H"
							}
							"HitMarkerShape38"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape38"
								"xpos"						"160"
								"ypos"						"60"
								"command"					"engine ih_hitmarker_shape_38"
								"labelText"					"I"
							}
							"HitMarkerShape39"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape39"
								"xpos"						"180"
								"ypos"						"60"
								"command"					"engine ih_hitmarker_shape_39"
								"labelText"					"J"
							}
							"HitMarkerShape40"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape40"
								"xpos"						"0"
								"ypos"						"80"
								"command"					"engine ih_hitmarker_shape_40"
								"labelText"					"K"
							}
							"HitMarkerShape41"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape41"
								"xpos"						"20"
								"ypos"						"80"
								"command"					"engine ih_hitmarker_shape_41"
								"labelText"					"L"
							}
							"HitMarkerShape42"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape42"
								"xpos"						"40"
								"ypos"						"80"
								"command"					"engine ih_hitmarker_shape_42"
								"labelText"					"M"
							}
							"HitMarkerShape43"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape43"
								"xpos"						"60"
								"ypos"						"80"
								"command"					"engine ih_hitmarker_shape_43"
								"labelText"					"N"
							}
							"HitMarkerShape44"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape44"
								"xpos"						"80"
								"ypos"						"80"
								"command"					"engine ih_hitmarker_shape_44"
								"labelText"					"O"
							}
							"HitMarkerShape45"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape45"
								"xpos"						"100"
								"ypos"						"80"
								"command"					"engine ih_hitmarker_shape_45"
								"labelText"					"P"
							}
							"HitMarkerShape46"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape46"
								"xpos"						"120"
								"ypos"						"80"
								"command"					"engine ih_hitmarker_shape_46"
								"labelText"					"Q"
							}
							"HitMarkerShape47"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape47"
								"xpos"						"140"
								"ypos"						"80"
								"command"					"engine ih_hitmarker_shape_47"
								"labelText"					"R"
							}
							"HitMarkerShape48"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape48"
								"xpos"						"160"
								"ypos"						"80"
								"command"					"engine ih_hitmarker_shape_48"
								"labelText"					"S"
							}
							"HitMarkerShape49"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape49"
								"xpos"						"180"
								"ypos"						"80"
								"command"					"engine ih_hitmarker_shape_49"
								"labelText"					"T"
							}
							"HitMarkerShape50"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape50"
								"xpos"						"0"
								"ypos"						"100"
								"command"					"engine ih_hitmarker_shape_50"
								"labelText"					"U"
							}
							"HitMarkerShape51"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape51"
								"xpos"						"20"
								"ypos"						"100"
								"command"					"engine ih_hitmarker_shape_51"
								"labelText"					"V"
							}
							"HitMarkerShape52"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape52"
								"xpos"						"40"
								"ypos"						"100"
								"command"					"engine ih_hitmarker_shape_52"
								"labelText"					"W"
							}
							"HitMarkerShape53"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape53"
								"xpos"						"60"
								"ypos"						"100"
								"command"					"engine ih_hitmarker_shape_53"
								"labelText"					"X"
							}
							"HitMarkerShape54"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape54"
								"xpos"						"80"
								"ypos"						"100"
								"command"					"engine ih_hitmarker_shape_54"
								"labelText"					"Y"
							}
							"HitMarkerShape55"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape55"
								"xpos"						"100"
								"ypos"						"100"
								"command"					"engine ih_hitmarker_shape_55"
								"labelText"					"Z"
							}
							"HitMarkerShape56"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape56"
								"xpos"						"120"
								"ypos"						"100"
								"command"					"engine ih_hitmarker_shape_56"
								"labelText"					"["
							}
							"HitMarkerShape57"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape57"
								"xpos"						"140"
								"ypos"						"100"
								"command"					"engine ih_hitmarker_shape_57"
								"labelText"					"\"
							}
							"HitMarkerShape58"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape58"
								"xpos"						"160"
								"ypos"						"100"
								"command"					"engine ih_hitmarker_shape_58"
								"labelText"					"]"
							}
							"HitMarkerShape59"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape59"
								"xpos"						"180"
								"ypos"						"100"
								"command"					"engine ih_hitmarker_shape_59"
								"labelText"					"^"
							}
							"HitMarkerShape60"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape60"
								"xpos"						"0"
								"ypos"						"120"
								"command"					"engine ih_hitmarker_shape_60"
								"labelText"					"_"
							}
							"HitMarkerShape61"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape61"
								"xpos"						"20"
								"ypos"						"120"
								"command"					"engine ih_hitmarker_shape_61"
								"labelText"					"`"
							}
							"HitMarkerShape62"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape62"
								"xpos"						"40"
								"ypos"						"120"
								"command"					"engine ih_hitmarker_shape_62"
								"labelText"					"a"
							}
							"HitMarkerShape63"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape63"
								"xpos"						"60"
								"ypos"						"120"
								"command"					"engine ih_hitmarker_shape_63"
								"labelText"					"b"
							}
							"HitMarkerShape64"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape64"
								"xpos"						"80"
								"ypos"						"120"
								"command"					"engine ih_hitmarker_shape_64"
								"labelText"					"c"
							}
							"HitMarkerShape65"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape65"
								"xpos"						"100"
								"ypos"						"120"
								"command"					"engine ih_hitmarker_shape_65"
								"labelText"					"d"
							}
							"HitMarkerShape66"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape66"
								"xpos"						"120"
								"ypos"						"120"
								"command"					"engine ih_hitmarker_shape_66"
								"labelText"					"e"
							}
							"HitMarkerShape67"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape67"
								"xpos"						"140"
								"ypos"						"120"
								"command"					"engine ih_hitmarker_shape_67"
								"labelText"					"f"
							}
							"HitMarkerShape68"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape68"
								"xpos"						"160"
								"ypos"						"120"
								"command"					"engine ih_hitmarker_shape_68"
								"labelText"					"g"
							}
							"HitMarkerShape69"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape69"
								"xpos"						"180"
								"ypos"						"120"
								"command"					"engine ih_hitmarker_shape_69"
								"labelText"					"h"
							}
							"HitMarkerShape70"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape70"
								"xpos"						"0"
								"ypos"						"140"
								"command"					"engine ih_hitmarker_shape_70"
								"labelText"					"i"
							}
							"HitMarkerShape71"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape71"
								"xpos"						"20"
								"ypos"						"140"
								"command"					"engine ih_hitmarker_shape_71"
								"labelText"					"j"
							}
							"HitMarkerShape72"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape72"
								"xpos"						"40"
								"ypos"						"140"
								"command"					"engine ih_hitmarker_shape_72"
								"labelText"					"k"
							}
							"HitMarkerShape73"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape73"
								"xpos"						"60"
								"ypos"						"140"
								"command"					"engine ih_hitmarker_shape_73"
								"labelText"					"l"
							}
							"HitMarkerShape74"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape74"
								"xpos"						"80"
								"ypos"						"140"
								"command"					"engine ih_hitmarker_shape_74"
								"labelText"					"m"
							}
							"HitMarkerShape75"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape75"
								"xpos"						"100"
								"ypos"						"140"
								"command"					"engine ih_hitmarker_shape_75"
								"labelText"					"n"
							}
							"HitMarkerShape76"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape76"
								"xpos"						"120"
								"ypos"						"140"
								"command"					"engine ih_hitmarker_shape_76"
								"labelText"					"o"
							}
							"HitMarkerShape77"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape77"
								"xpos"						"140"
								"ypos"						"140"
								"command"					"engine ih_hitmarker_shape_77"
								"labelText"					"p"
							}
							"HitMarkerShape78"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape78"
								"xpos"						"160"
								"ypos"						"140"
								"command"					"engine ih_hitmarker_shape_78"
								"labelText"					"q"
							}
							"HitMarkerShape79"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape79"
								"xpos"						"180"
								"ypos"						"140"
								"command"					"engine ih_hitmarker_shape_79"
								"labelText"					"r"
							}
							"HitMarkerShape80"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape80"
								"xpos"						"0"
								"ypos"						"160"
								"command"					"engine ih_hitmarker_shape_80"
								"labelText"					"s"
							}
							"HitMarkerShape81"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape81"
								"xpos"						"20"
								"ypos"						"160"
								"command"					"engine ih_hitmarker_shape_81"
								"labelText"					"t"
							}
							"HitMarkerShape82"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape82"
								"xpos"						"40"
								"ypos"						"160"
								"command"					"engine ih_hitmarker_shape_82"
								"labelText"					"u"
							}
							"HitMarkerShape83"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape83"
								"xpos"						"60"
								"ypos"						"160"
								"command"					"engine ih_hitmarker_shape_83"
								"labelText"					"v"
							}
							"HitMarkerShape84"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape84"
								"xpos"						"80"
								"ypos"						"160"
								"command"					"engine ih_hitmarker_shape_84"
								"labelText"					"w"
							}
							"HitMarkerShape85"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape85"
								"xpos"						"100"
								"ypos"						"160"
								"command"					"engine ih_hitmarker_shape_85"
								"labelText"					"x"
							}
							"HitMarkerShape86"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape86"
								"xpos"						"120"
								"ypos"						"160"
								"command"					"engine ih_hitmarker_shape_86"
								"labelText"					"y"
							}
							"HitMarkerShape87"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape87"
								"xpos"						"140"
								"ypos"						"160"
								"command"					"engine ih_hitmarker_shape_87"
								"labelText"					"z"
							}
							"HitMarkerShape88"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_1"
								"border_armed"				"FLAT_Black_1"
								"defaultFgColor_override"	"TextT4"
								"armedfgcolor_override"		"TextT4"
								"fieldName"					"HitmarkerShape88"
								"xpos"						"160"
								"ypos"						"160"
								"command"					"engine clear; showconsole; echo Disabled temporarily due to a bug."
								"labelText"					"{"
							}
							"HitMarkerShape89"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape89"
								"xpos"						"180"
								"ypos"						"160"
								"command"					"engine ih_hitmarker_shape_89"
								"labelText"					"|"
							}
							"HitMarkerShape90"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_1"
								"border_armed"				"FLAT_Black_1"
								"defaultFgColor_override"	"TextT4"
								"armedfgcolor_override"		"TextT4"
								"fieldName"					"HitmarkerShape90"
								"xpos"						"0"
								"ypos"						"180"
								"command"					"engine clear; showconsole; echo Disabled temporarily due to a bug."
								"labelText"					"}"
							}
							"HitMarkerShape91"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"HitmarkerShape91"
								"xpos"						"20"
								"ypos"						"180"
								"command"					"engine ih_hitmarker_shape_91"
								"labelText"					"~"
							}
						}
					}
				}
			}
		}
	}
}
