"Scheme"
{
	"Borders"
	{
		"NONE_Black_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Black_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_1"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Black_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_2"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Black_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_3"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Black_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_4"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_White_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_White_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_1"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_White_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_2"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_White_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_3"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_White_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_4"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_1"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_2"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_3"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_4"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Positive_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Positive_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_1"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Positive_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_2"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Positive_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_3"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Positive_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_4"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Warning_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Warning_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_1"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Warning_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_2"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Warning_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_3"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Warning_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_4"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Negative_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Negative_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_1"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Negative_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_2"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Negative_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_3"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_Negative_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_4"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_PanelO0_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_PanelO1_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_PanelO2_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_PanelO3_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_PanelO4_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_PanelO5_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_PanelO6_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_1"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_2"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_3"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_4"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_0"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_1"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_2"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_3"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"NONE_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/rounded_rect/NONE_4"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
	}
}
