"Scheme"
{
	"Borders"
	{
		"LINE_BOTTOM_0_Primary_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_Primary_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_Primary_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/0/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_Primary_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/0/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_Primary_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/0/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_Primary_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/0/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_Primary_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/0/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_Primary_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/0/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_Primary_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_Primary_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_Primary_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/1/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_Primary_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/1/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_Primary_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/1/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_Primary_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/1/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_Primary_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/1/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_Primary_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Primary"
			"image" "replay/thumbnails/panels/line/1/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_White_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_White_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_White_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/0/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_White_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/0/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_White_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/0/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_White_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/0/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_White_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/0/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_White_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/0/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_White_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_White_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_White_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/1/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_White_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/1/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_White_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/1/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_White_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/1/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_White_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/1/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_White_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "White"
			"image" "replay/thumbnails/panels/line/1/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_Positive_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_Positive_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_Positive_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/0/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_Positive_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/0/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_Positive_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/0/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_Positive_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/0/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_Positive_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/0/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_Positive_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/0/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_Positive_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_Positive_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_Positive_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/1/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_Positive_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/1/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_Positive_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/1/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_Positive_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/1/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_Positive_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/1/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_Positive_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Positive"
			"image" "replay/thumbnails/panels/line/1/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_Warning_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_Warning_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_Warning_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/0/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_Warning_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/0/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_Warning_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/0/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_Warning_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/0/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_Warning_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/0/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_Warning_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/0/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_Warning_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_Warning_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_Warning_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/1/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_Warning_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/1/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_Warning_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/1/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_Warning_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/1/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_Warning_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/1/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_Warning_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Warning"
			"image" "replay/thumbnails/panels/line/1/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_Negative_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_Negative_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_Negative_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/0/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_Negative_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/0/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_Negative_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/0/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_Negative_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/0/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_Negative_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/0/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_Negative_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/0/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_Negative_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_Negative_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_Negative_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/1/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_Negative_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/1/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_Negative_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/1/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_Negative_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/1/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_Negative_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/1/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_Negative_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "Negative"
			"image" "replay/thumbnails/panels/line/1/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_m0reRed_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_m0reRed_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_m0reRed_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/0/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_m0reRed_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/0/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_m0reRed_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/0/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_m0reRed_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/0/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_m0reRed_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/0/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_m0reRed_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/0/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_m0reRed_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_m0reRed_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_m0reRed_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/1/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_m0reRed_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/1/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_m0reRed_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/1/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_m0reRed_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/1/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_m0reRed_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/1/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_m0reRed_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reRed"
			"image" "replay/thumbnails/panels/line/1/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_m0reBlue_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_m0reBlue_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/0/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_m0reBlue_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/0/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_m0reBlue_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/0/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_m0reBlue_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/0/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_m0reBlue_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/0/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_m0reBlue_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/0/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_m0reBlue_0"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/0/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_0_m0reBlue_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_BOTTOM_3_m0reBlue_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/1/BOTTOM_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_0_m0reBlue_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/1/LEFT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_LEFT_3_m0reBlue_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/1/LEFT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_0_m0reBlue_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/1/RIGHT_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_RIGHT_3_m0reBlue_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/1/RIGHT_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_0_m0reBlue_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/1/TOP_0"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
		"LINE_TOP_3_m0reBlue_1"
		{
			"bordertype" "scalable_image"
			"backgroundtype" "0"
			"color" "m0reBlue"
			"image" "replay/thumbnails/panels/line/1/TOP_3"
			"src_corner_width" "12"
			"src_corner_height" "12"
			"draw_corner_width" "2"
			"draw_corner_height" "2"
		}
	}
}
