"Scheme"
{
	"Borders"
	{
		"LINE_BOTTOM_Black_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Black_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Black_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Black_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Black_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Black_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Black_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Black_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Black_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Black_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Black_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Black_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Black_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Black_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Black_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Black_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Black_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Black_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Black_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Black_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO0_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO0_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO0_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO0_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO0_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO0_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO0_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO0_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO0_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO0_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO0_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO0_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO0_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO0_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO0_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO0_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO0_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO0_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO0_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO0_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO1_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO1_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO1_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO1_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO1_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO1_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO1_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO1_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO1_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO1_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO1_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO1_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO1_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO1_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO1_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO1_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO1_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO1_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO1_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO1_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO2_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO2_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO2_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO2_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO2_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO2_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO2_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO2_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO2_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO2_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO2_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO2_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO2_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO2_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO2_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO2_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO2_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO2_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO2_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO2_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO3_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO3_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO3_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO3_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO3_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO3_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO3_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO3_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO3_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO3_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO3_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO3_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO3_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO3_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO3_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO3_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO3_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO3_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO3_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO3_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO4_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO4_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO4_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO4_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO4_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO4_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO4_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO4_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO4_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO4_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO4_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO4_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO4_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO4_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO4_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO4_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO4_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO4_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO4_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO4_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO5_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO5_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO5_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO5_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO5_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO5_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO5_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO5_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO5_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO5_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO5_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO5_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO5_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO5_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO5_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO5_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO5_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO5_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO5_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO5_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO6_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO6_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO6_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO6_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO6_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO6_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO6_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO6_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO6_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO6_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO6_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO6_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO6_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO6_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO6_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO6_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_PanelO6_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_PanelO6_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_PanelO6_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_PanelO6_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_BOTTOM_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_LEFT_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/LEFT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_RIGHT_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/RIGHT"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
		"LINE_TOP_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/TOP"
			"src_corner_width"			"20"
			"src_corner_height"			"20"
			"draw_corner_width"			"4"
			"draw_corner_height"		"4"
		}
	}
}
