"Scheme"
{
	"Borders"
	{
		"LINE_BOTTOM_GLOW_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_White_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/0/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_White_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/1/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_White_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/2/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_White_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/3/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_White_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/4/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_White_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/5/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_White_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/5/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_White_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/5/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_White_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/line/5/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_AccentMain_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/0/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_AccentMain_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/1/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_AccentMain_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/2/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_AccentMain_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/3/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_AccentMain_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/4/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_AccentMain_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/5/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_AccentMain_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/5/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_AccentMain_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/5/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_AccentMain_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"AccentMain"
			"image"						"replay/thumbnails/panels/line/5/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Positive_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/0/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Positive_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/1/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Positive_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/2/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Positive_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/3/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Positive_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/4/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Positive_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/5/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Positive_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/5/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Positive_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/5/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Positive_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/line/5/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Warning_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/0/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Warning_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/1/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Warning_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/2/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Warning_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/3/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Warning_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/4/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Warning_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/5/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Warning_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/5/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Warning_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/5/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Warning_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/line/5/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Negative_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/0/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Negative_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/1/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Negative_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/2/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Negative_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/3/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_Negative_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/4/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_Negative_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/5/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_Negative_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/5/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_Negative_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/5/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_Negative_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/line/5/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/0/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/1/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/2/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/3/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/4/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reRed_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/5/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reRed_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/5/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reRed_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/5/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reRed_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/line/5/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/0/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/1/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/2/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/3/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_NOGLOW_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/BOTTOM_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_NOGLOW_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/LEFT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_NOGLOW_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/RIGHT_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_NOGLOW_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/4/TOP_NOGLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_BOTTOM_GLOW_m0reBlue_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/5/BOTTOM_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_LEFT_GLOW_m0reBlue_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/5/LEFT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_RIGHT_GLOW_m0reBlue_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/5/RIGHT_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
		"LINE_TOP_GLOW_m0reBlue_5"
		{
			"bordertype"				"scalable_image"
			"backgroundtype"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/line/5/TOP_GLOW"
			"src_corner_width"			"30"
			"src_corner_height"			"30"
			"draw_corner_width"			"5"
			"draw_corner_height"		"5"
		}
	}
}
