"Scheme"
{
	"Borders"
	{
		"FLAT_Black_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Black_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/FLAT_1"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Black_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/FLAT_2"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Black_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/FLAT_3"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Black_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Black"
			"image"						"replay/thumbnails/panels/FLAT_4"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_White_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_White_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/FLAT_1"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_White_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/FLAT_2"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_White_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/FLAT_3"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_White_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"White"
			"image"						"replay/thumbnails/panels/FLAT_4"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Primary_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Primary"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Primary_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Primary"
			"image"						"replay/thumbnails/panels/FLAT_1"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Primary_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Primary"
			"image"						"replay/thumbnails/panels/FLAT_2"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Primary_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Primary"
			"image"						"replay/thumbnails/panels/FLAT_3"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Primary_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Primary"
			"image"						"replay/thumbnails/panels/FLAT_4"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Positive_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Positive_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/FLAT_1"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Positive_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/FLAT_2"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Positive_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/FLAT_3"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Positive_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Positive"
			"image"						"replay/thumbnails/panels/FLAT_4"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Warning_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Warning_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/FLAT_1"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Warning_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/FLAT_2"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Warning_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/FLAT_3"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Warning_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Warning"
			"image"						"replay/thumbnails/panels/FLAT_4"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Negative_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Negative_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/FLAT_1"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Negative_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/FLAT_2"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Negative_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/FLAT_3"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_Negative_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"Negative"
			"image"						"replay/thumbnails/panels/FLAT_4"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_PanelO0_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO0"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_PanelO1_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO1"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_PanelO2_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO2"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_PanelO3_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO3"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_PanelO4_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO4"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_PanelO5_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO5"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_PanelO6_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"PanelO6"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_m0reRed_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_m0reRed_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/FLAT_1"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_m0reRed_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/FLAT_2"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_m0reRed_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/FLAT_3"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_m0reRed_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reRed"
			"image"						"replay/thumbnails/panels/FLAT_4"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_m0reBlue_0"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/FLAT_0"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_m0reBlue_1"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/FLAT_1"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_m0reBlue_2"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/FLAT_2"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_m0reBlue_3"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/FLAT_3"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
		"FLAT_m0reBlue_4"
		{
			"bordertype"				"scalable_image"
			"background_type"			"0"
			"color"						"m0reBlue"
			"image"						"replay/thumbnails/panels/FLAT_4"
			"src_corner_width"			"12"
			"src_corner_height"			"12"
			"draw_corner_width"			"2"
			"draw_corner_height"		"2"
		}
	}
}
