"Resource/UI/MainMenuOverride.res"
{
	"CustomizationMenu"
	{
		"MainPanel"
		{
			"MenuContainer"
			{
				"ColorButtons"
				{
					"C0"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C0"
						"xpos"							"0"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_0"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 64 255"
						"armedbgcolor_override"			"255 64 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C1"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C1"
						"xpos"							"4"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_1"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 74 64 255"
						"armedbgcolor_override"			"255 74 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C2"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C2"
						"xpos"							"8"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_2"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 84 64 255"
						"armedbgcolor_override"			"255 84 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C3"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C3"
						"xpos"							"12"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_3"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 95 64 255"
						"armedbgcolor_override"			"255 95 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C4"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C4"
						"xpos"							"16"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_4"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 105 64 255"
						"armedbgcolor_override"			"255 105 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C5"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C5"
						"xpos"							"20"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_5"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 115 64 255"
						"armedbgcolor_override"			"255 115 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C6"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C6"
						"xpos"							"24"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_6"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 126 64 255"
						"armedbgcolor_override"			"255 126 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C7"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C7"
						"xpos"							"28"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_7"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 136 64 255"
						"armedbgcolor_override"			"255 136 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C8"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C8"
						"xpos"							"32"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_8"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 146 64 255"
						"armedbgcolor_override"			"255 146 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C9"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C9"
						"xpos"							"36"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_9"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 157 64 255"
						"armedbgcolor_override"			"255 157 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C10"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C10"
						"xpos"							"40"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_10"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 167 64 255"
						"armedbgcolor_override"			"255 167 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C11"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C11"
						"xpos"							"44"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_11"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 177 64 255"
						"armedbgcolor_override"			"255 177 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C12"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C12"
						"xpos"							"48"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_12"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 188 64 255"
						"armedbgcolor_override"			"255 188 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C13"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C13"
						"xpos"							"52"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_13"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 198 64 255"
						"armedbgcolor_override"			"255 198 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C14"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C14"
						"xpos"							"56"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_14"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 208 64 255"
						"armedbgcolor_override"			"255 208 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C15"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C15"
						"xpos"							"60"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_15"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 219 64 255"
						"armedbgcolor_override"			"255 219 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C16"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C16"
						"xpos"							"64"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_16"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 229 64 255"
						"armedbgcolor_override"			"255 229 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C17"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C17"
						"xpos"							"68"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_17"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 239 64 255"
						"armedbgcolor_override"			"255 239 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C18"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C18"
						"xpos"							"72"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_18"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 250 64 255"
						"armedbgcolor_override"			"255 250 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C19"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C19"
						"xpos"							"76"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_19"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"250 255 64 255"
						"armedbgcolor_override"			"250 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C20"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C20"
						"xpos"							"80"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_20"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"239 255 64 255"
						"armedbgcolor_override"			"239 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C21"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C21"
						"xpos"							"84"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_21"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"229 255 64 255"
						"armedbgcolor_override"			"229 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C22"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C22"
						"xpos"							"88"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_22"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"219 255 64 255"
						"armedbgcolor_override"			"219 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C23"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C23"
						"xpos"							"92"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_23"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"208 255 64 255"
						"armedbgcolor_override"			"208 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C24"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C24"
						"xpos"							"96"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_24"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"198 255 64 255"
						"armedbgcolor_override"			"198 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C25"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C25"
						"xpos"							"100"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_25"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"188 255 64 255"
						"armedbgcolor_override"			"188 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C26"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C26"
						"xpos"							"104"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_26"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"177 255 64 255"
						"armedbgcolor_override"			"177 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C27"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C27"
						"xpos"							"108"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_27"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"167 255 64 255"
						"armedbgcolor_override"			"167 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C28"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C28"
						"xpos"							"112"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_28"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"157 255 64 255"
						"armedbgcolor_override"			"157 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C29"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C29"
						"xpos"							"116"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_29"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"146 255 64 255"
						"armedbgcolor_override"			"146 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C30"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C30"
						"xpos"							"120"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_30"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"136 255 64 255"
						"armedbgcolor_override"			"136 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C31"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C31"
						"xpos"							"124"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_31"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"126 255 64 255"
						"armedbgcolor_override"			"126 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C32"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C32"
						"xpos"							"128"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_32"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"115 255 64 255"
						"armedbgcolor_override"			"115 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C33"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C33"
						"xpos"							"132"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_33"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"105 255 64 255"
						"armedbgcolor_override"			"105 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C34"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C34"
						"xpos"							"136"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_34"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"95 255 64 255"
						"armedbgcolor_override"			"95 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C35"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C35"
						"xpos"							"140"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_35"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"84 255 64 255"
						"armedbgcolor_override"			"84 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C36"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C36"
						"xpos"							"144"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_36"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"74 255 64 255"
						"armedbgcolor_override"			"74 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C37"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C37"
						"xpos"							"148"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_37"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 64 255"
						"armedbgcolor_override"			"64 255 64 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C38"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C38"
						"xpos"							"152"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_38"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 74 255"
						"armedbgcolor_override"			"64 255 74 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C39"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C39"
						"xpos"							"156"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_39"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 84 255"
						"armedbgcolor_override"			"64 255 84 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C40"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C40"
						"xpos"							"160"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_40"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 95 255"
						"armedbgcolor_override"			"64 255 95 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C41"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C41"
						"xpos"							"164"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_41"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 105 255"
						"armedbgcolor_override"			"64 255 105 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C42"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C42"
						"xpos"							"168"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_42"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 115 255"
						"armedbgcolor_override"			"64 255 115 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C43"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C43"
						"xpos"							"172"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_43"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 126 255"
						"armedbgcolor_override"			"64 255 126 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C44"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C44"
						"xpos"							"176"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_44"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 136 255"
						"armedbgcolor_override"			"64 255 136 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C45"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C45"
						"xpos"							"180"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_45"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 146 255"
						"armedbgcolor_override"			"64 255 146 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C46"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C46"
						"xpos"							"184"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_46"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 157 255"
						"armedbgcolor_override"			"64 255 157 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C47"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C47"
						"xpos"							"188"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_47"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 167 255"
						"armedbgcolor_override"			"64 255 167 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C48"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C48"
						"xpos"							"192"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_48"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 177 255"
						"armedbgcolor_override"			"64 255 177 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C49"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C49"
						"xpos"							"196"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_49"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 188 255"
						"armedbgcolor_override"			"64 255 188 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C50"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C50"
						"xpos"							"200"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_50"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 198 255"
						"armedbgcolor_override"			"64 255 198 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C51"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C51"
						"xpos"							"204"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_51"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 208 255"
						"armedbgcolor_override"			"64 255 208 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C52"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C52"
						"xpos"							"208"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_52"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 219 255"
						"armedbgcolor_override"			"64 255 219 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C53"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C53"
						"xpos"							"212"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_53"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 229 255"
						"armedbgcolor_override"			"64 255 229 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C54"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C54"
						"xpos"							"216"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_54"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 239 255"
						"armedbgcolor_override"			"64 255 239 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C55"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C55"
						"xpos"							"220"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_55"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 255 250 255"
						"armedbgcolor_override"			"64 255 250 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C56"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C56"
						"xpos"							"224"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_56"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 250 255 255"
						"armedbgcolor_override"			"64 250 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C57"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C57"
						"xpos"							"228"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_57"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 239 255 255"
						"armedbgcolor_override"			"64 239 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C58"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C58"
						"xpos"							"232"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_58"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 229 255 255"
						"armedbgcolor_override"			"64 229 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C59"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C59"
						"xpos"							"236"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_59"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 219 255 255"
						"armedbgcolor_override"			"64 219 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C60"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C60"
						"xpos"							"240"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_60"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 208 255 255"
						"armedbgcolor_override"			"64 208 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C61"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C61"
						"xpos"							"244"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_61"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 198 255 255"
						"armedbgcolor_override"			"64 198 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C62"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C62"
						"xpos"							"248"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_62"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 188 255 255"
						"armedbgcolor_override"			"64 188 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C63"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C63"
						"xpos"							"252"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_63"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 177 255 255"
						"armedbgcolor_override"			"64 177 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C64"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C64"
						"xpos"							"256"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_64"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 167 255 255"
						"armedbgcolor_override"			"64 167 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C65"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C65"
						"xpos"							"260"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_65"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 157 255 255"
						"armedbgcolor_override"			"64 157 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C66"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C66"
						"xpos"							"264"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_66"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 146 255 255"
						"armedbgcolor_override"			"64 146 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C67"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C67"
						"xpos"							"268"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_67"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 136 255 255"
						"armedbgcolor_override"			"64 136 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C68"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C68"
						"xpos"							"272"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_68"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 126 255 255"
						"armedbgcolor_override"			"64 126 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C69"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C69"
						"xpos"							"276"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_69"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 115 255 255"
						"armedbgcolor_override"			"64 115 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C70"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C70"
						"xpos"							"280"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_70"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 105 255 255"
						"armedbgcolor_override"			"64 105 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C71"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C71"
						"xpos"							"284"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_71"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 95 255 255"
						"armedbgcolor_override"			"64 95 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C72"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C72"
						"xpos"							"288"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_72"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 84 255 255"
						"armedbgcolor_override"			"64 84 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C73"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C73"
						"xpos"							"292"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_73"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 74 255 255"
						"armedbgcolor_override"			"64 74 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C74"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C74"
						"xpos"							"296"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_74"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"64 64 255 255"
						"armedbgcolor_override"			"64 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C75"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C75"
						"xpos"							"300"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_75"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"74 64 255 255"
						"armedbgcolor_override"			"74 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C76"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C76"
						"xpos"							"304"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_76"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"84 64 255 255"
						"armedbgcolor_override"			"84 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C77"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C77"
						"xpos"							"308"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_77"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"95 64 255 255"
						"armedbgcolor_override"			"95 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C78"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C78"
						"xpos"							"312"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_78"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"105 64 255 255"
						"armedbgcolor_override"			"105 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C79"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C79"
						"xpos"							"316"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_79"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"115 64 255 255"
						"armedbgcolor_override"			"115 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C80"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C80"
						"xpos"							"320"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_80"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"126 64 255 255"
						"armedbgcolor_override"			"126 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C81"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C81"
						"xpos"							"324"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_81"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"136 64 255 255"
						"armedbgcolor_override"			"136 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C82"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C82"
						"xpos"							"328"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_82"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"146 64 255 255"
						"armedbgcolor_override"			"146 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C83"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C83"
						"xpos"							"332"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_83"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"157 64 255 255"
						"armedbgcolor_override"			"157 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C84"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C84"
						"xpos"							"336"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_84"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"167 64 255 255"
						"armedbgcolor_override"			"167 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C85"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C85"
						"xpos"							"340"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_85"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"177 64 255 255"
						"armedbgcolor_override"			"177 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C86"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C86"
						"xpos"							"344"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_86"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"188 64 255 255"
						"armedbgcolor_override"			"188 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C87"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C87"
						"xpos"							"348"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_87"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"198 64 255 255"
						"armedbgcolor_override"			"198 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C88"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C88"
						"xpos"							"352"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_88"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"208 64 255 255"
						"armedbgcolor_override"			"208 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C89"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C89"
						"xpos"							"356"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_89"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"219 64 255 255"
						"armedbgcolor_override"			"219 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C90"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C90"
						"xpos"							"360"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_90"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"229 64 255 255"
						"armedbgcolor_override"			"229 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C91"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C91"
						"xpos"							"364"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_91"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"239 64 255 255"
						"armedbgcolor_override"			"239 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C92"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C92"
						"xpos"							"368"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_92"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"250 64 255 255"
						"armedbgcolor_override"			"250 64 255 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C93"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C93"
						"xpos"							"372"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_93"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 250 255"
						"armedbgcolor_override"			"255 64 250 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C94"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C94"
						"xpos"							"376"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_94"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 239 255"
						"armedbgcolor_override"			"255 64 239 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C95"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C95"
						"xpos"							"380"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_95"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 229 255"
						"armedbgcolor_override"			"255 64 229 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C96"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C96"
						"xpos"							"384"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_96"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 219 255"
						"armedbgcolor_override"			"255 64 219 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C97"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C97"
						"xpos"							"388"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_97"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 208 255"
						"armedbgcolor_override"			"255 64 208 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C98"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C98"
						"xpos"							"392"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_98"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 198 255"
						"armedbgcolor_override"			"255 64 198 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C99"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C99"
						"xpos"							"396"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_99"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 188 255"
						"armedbgcolor_override"			"255 64 188 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C100"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C100"
						"xpos"							"400"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_100"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 177 255"
						"armedbgcolor_override"			"255 64 177 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C101"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C101"
						"xpos"							"404"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_101"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 167 255"
						"armedbgcolor_override"			"255 64 167 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C102"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C102"
						"xpos"							"408"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_102"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 157 255"
						"armedbgcolor_override"			"255 64 157 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C103"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C103"
						"xpos"							"412"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_103"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 146 255"
						"armedbgcolor_override"			"255 64 146 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C104"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C104"
						"xpos"							"416"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_104"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 136 255"
						"armedbgcolor_override"			"255 64 136 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C105"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C105"
						"xpos"							"420"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_105"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 126 255"
						"armedbgcolor_override"			"255 64 126 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C106"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C106"
						"xpos"							"424"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_106"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 115 255"
						"armedbgcolor_override"			"255 64 115 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C107"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C107"
						"xpos"							"428"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_107"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 105 255"
						"armedbgcolor_override"			"255 64 105 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C108"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C108"
						"xpos"							"432"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_108"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 95 255"
						"armedbgcolor_override"			"255 64 95 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
					"C109"
					{
						"ControlName"					"CExButton"
						"fieldName"						"C109"
						"xpos"							"436"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"480"
						"proportionaltoparent"			"1"
						"labeltext"						""
						"paintbackground"				"1"
						"command"						"engine ih_accent_109"
						"actionsignallevel"				"5"
						"defaultbgcolor_override"		"255 64 84 255"
						"armedbgcolor_override"			"255 64 84 153"
						"sound_depressed"				"UI/buttonclick.wav"
						"sound_released"				"UI/buttonclickrelease.wav"
					}
				}
			}
		}
	}
}
