"#base"		"customization_menu_submenus/accent_color/accent_color.res"
"#base"		"customization_menu_submenus/crosshair/crosshair.res"
"#base"		"customization_menu_submenus/hitmarker/hitmarker.res"
"#base"		"customization_menu_submenus/scoreboard/scoreboard.res"
"#base"		"customization_menu_submenus/health_ammo/health_ammo.res"
"Resource/UI/MainMenuOverride.res"
{
	"MainMenuOverride"
	{
		"CustomizationMenu"
		{
			"ControlName"			"EditablePanel"
			"fieldName"				"CustomizationMenu"
			"xpos"					"0"
			"ypos"					"0"
			"zpos"					"11000"
			"wide"					"f0"
			"tall"					"f0"
			"bgcolor_override"		"PanelO0"
			"MenuColorizer"
			{
				"ControlName"			"EditablePanel"
				"fieldName"				"MenuColorizer"
				"xpos"					"0"
				"ypos"					"0"
				"wide"					"f0"
				"tall"					"480"
				"visible"				"1"
				"enabled"				"1"
				"mouseinputenabled"		"0"
				"SubImage"
				{
					"ControlName"				"CTFImagePanel"
					"fieldName"					"SubImage"
					"xpos"						"0"
					"ypos"						"0"
					"wide"						"f0"
					"tall"						"f0"
					"proportionaltoparent"		"1"
					"scaleImage"				"1"
					"image"						"replay/thumbnails/ui_effects/menu_glow"
					"drawcolor"					"AccentMain"
				}
			}
			"MenuColorizer2"
			{
				"ControlName"			"EditablePanel"
				"fieldName"				"MenuColorizer2"
				"xpos"					"0"
				"ypos"					"0"
				"wide"					"f0"
				"tall"					"480"
				"visible"				"1"
				"enabled"				"1"
				"mouseinputenabled"		"0"
				"SubImage"
				{
					"ControlName"				"CTFImagePanel"
					"fieldName"					"SubImage"
					"xpos"						"0"
					"ypos"						"0"
					"wide"						"f0"
					"tall"						"f0"
					"proportionaltoparent"		"1"
					"scaleImage"				"1"
					"image"						"replay/thumbnails/ui_effects/menu_glow_alt"
					"drawcolor"					"AccentMain"
				}
			}
			"MainPanel"
			{
				"ControlName"				"EditablePanel"
				"fieldName"					"MainPanel"
				"xpos"						"cs-0.5"
				"ypos"						"10"
				"zpos"						"50"
				"wide"						"630"
				"tall"						"460"
				"proportionaltoparent"		"1"
				"paintbackground"			"1"
				"border"					"FLAT_Black_1"
				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"0"
					"ypos"						"0"
					"wide"						"f0"
					"tall"						"20"
					"proportionaltoparent"		"1"
					"font"						"regular14"
					"labelText"					"CUSTOMIZE"
					"textAlignment"				"center"
					"fgcolor"					"AccentMain"
					"border"					"NoBorder"
				}
				"RestartWarning"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"RestartWarning"
					"xpos"						"0"
					"ypos"						"rs1"
					"wide"						"f0"
					"tall"						"20"
					"proportionaltoparent"		"1"
					"font"						"regular12"
					"labelText"					"NOTICE: Some changes (such as color related ones) require game restart in order to take effect."
					"textAlignment"				"center"
					"fgcolor"					"TextT4"
					"border"					"NoBorder"
				}
				"SectionContainer"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"SectionContainer"
					"xpos"						"0"
					"ypos"						"20"
					"wide"						"f0"
					"tall"						"f40"
					"proportionaltoparent"		"1"
					"paintbackground"			"0"
				}
				"Back"
				{
					"ControlName"					"CExButton"
					"fieldName"						"Back"
					"xpos"							"rs1"
					"ypos"							"0"
					"wide"							"20"
					"tall"							"20"
					"proportionaltoparent"			"1"
					"paintbackground"				"0"
					"font"							"iconsSmall"
					"labelText"						"x"
					"textalignment"					"center"
					"command"						"engine ih_custom_off; ih_reloadmenus"
					"actionsignallevel"				"3"
					"sound_depressed"				"UI/buttonclick.wav"
					"sound_released"				"UI/buttonclickrelease.wav"
					"defaultFgColor_override"		"AccentMain"
					"armedFgColor_override"			"AccentMain"
					"border_default"				"NoBorder"
					"border_armed"					"FLAT_AccentMain_4"
				}
			}
			"MainPanelColor"
			{
				"ControlName"				"EditablePanel"
				"fieldName"					"MainPanelColor"
				"xpos"						"cs-0.5"
				"ypos"						"10"
				"zpos"						"49"
				"wide"						"630"
				"tall"						"460"
				"proportionaltoparent"		"1"
				"paintbackground"			"1"
				"border"					"FLAT_AccentMain_4"
			}
		}
	}
}
