"#base"		"customization_menu_submenus/color.res"
"Resource/UI/MainMenuOverride.res"
{
	"MainMenuOverride"
	{
		"CustomizationMenu"
		{
			"ControlName"			"EditablePanel"
			"fieldName"				"CustomizationMenu"
			"xpos"					"0"
			"ypos"					"0"
			"zpos"					"11000"
			"wide"					"f0"
			"tall"					"f0"
			"bgcolor_override"		"PanelO0"
			"GlowEffect"
			{
				"ControlName"				"CTFImagePanel"
				"fieldName"					"GlowEffect"
				"xpos"						"0"
				"ypos"						"0"
				"wide"						"f0"
				"tall"						"f0"
				"proportionaltoparent"		"1"
				"scaleImage"				"1"
				"image"						"replay/thumbnails/ui_effects/menu_glow"
				"drawcolor"					"White"
				"alpha"						"128"
			}
			"MainPanel"
			{
				"ControlName"				"EditablePanel"
				"fieldName"					"MainPanel"
				"xpos"						"cs-0.5"
				"ypos"						"20"
				"wide"						"600"
				"tall"						"440"
				"proportionaltoparent"		"1"
				"paintbackground"			"0"
				"border"					"TLTRBLBR_PanelO3_0"
				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"0"
					"ypos"						"0"
					"wide"						"f0"
					"tall"						"20"
					"proportionaltoparent"		"1"
					"font"						"bold18"
					"labelText"					"CUSTOMIZE"
					"textAlignment"				"center"
					"fgcolor"					"Text0"
					"border"					"TLTR_PanelO1_0"
				}
				"SectionContainer"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"SectionContainer"
					"xpos"						"0"
					"ypos"						"20"
					"wide"						"600"
					"tall"						"400"
					"proportionaltoparent"		"1"
					"paintbackground"			"0"
				}
				"DiscardAndExit"
				{
					"ControlName"				"URLLabel"
					"fieldName"					"DiscardAndExit"
					"xpos"						"0"
					"ypos"						"rs1"
					"wide"						"p0.5"
					"tall"						"20"
					"proportionaltoparent"		"1"
					"paintbackground"			"0"
					"font"						"bold18"
					"textalignment"				"center"
					"labeltext"					"DISCARD CHANGES"
					"urltext"					"tf\custom\insomniaHUD\customization\dev\discard_changes.bat"
				}
				"SaveAndExit"
				{
					"ControlName"				"URLLabel"
					"fieldName"					"SaveAndExit"
					"xpos"						"p0.5"
					"ypos"						"rs1"
					"wide"						"p0.5"
					"tall"						"20"
					"proportionaltoparent"		"1"
					"paintbackground"			"0"
					"font"						"bold18"
					"textalignment"				"center"
					"labeltext"					"APPLY CHANGES"
					"urltext"					"tf\custom\insomniaHUD\customization\dev\apply_changes.bat"
				}
			}
		}
	}
}
