"Resource/UI/MainMenuOverride.res"
{
	"MainMenuOverride"
	{
		"CustomizationMenu"
		{
			"MainPanel"
			{
				"SectionContainer"
				{
					"AccentColor"
					{
						"Buttons"
						{
							"C0"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C0"
								"xpos"							"0"
								"ypos"							"0"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_0"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 64 255"
								"armedbgcolor_override"			"255 64 64 204"
							}
							"C1"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C1"
								"xpos"							"20"
								"ypos"							"0"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_1"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 70 64 255"
								"armedbgcolor_override"			"255 70 64 204"
							}
							"C2"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C2"
								"xpos"							"40"
								"ypos"							"0"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_2"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 76 64 255"
								"armedbgcolor_override"			"255 76 64 204"
							}
							"C3"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C3"
								"xpos"							"60"
								"ypos"							"0"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_3"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 83 64 255"
								"armedbgcolor_override"			"255 83 64 204"
							}
							"C4"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C4"
								"xpos"							"80"
								"ypos"							"0"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_4"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 89 64 255"
								"armedbgcolor_override"			"255 89 64 204"
							}
							"C5"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C5"
								"xpos"							"100"
								"ypos"							"0"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_5"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 95 64 255"
								"armedbgcolor_override"			"255 95 64 204"
							}
							"C6"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C6"
								"xpos"							"120"
								"ypos"							"0"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_6"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 102 64 255"
								"armedbgcolor_override"			"255 102 64 204"
							}
							"C7"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C7"
								"xpos"							"140"
								"ypos"							"0"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_7"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 108 64 255"
								"armedbgcolor_override"			"255 108 64 204"
							}
							"C8"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C8"
								"xpos"							"160"
								"ypos"							"0"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_8"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 114 64 255"
								"armedbgcolor_override"			"255 114 64 204"
							}
							"C9"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C9"
								"xpos"							"180"
								"ypos"							"0"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_9"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 121 64 255"
								"armedbgcolor_override"			"255 121 64 204"
							}
							"C10"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C10"
								"xpos"							"0"
								"ypos"							"20"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_10"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 127 64 255"
								"armedbgcolor_override"			"255 127 64 204"
							}
							"C11"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C11"
								"xpos"							"20"
								"ypos"							"20"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_11"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 133 64 255"
								"armedbgcolor_override"			"255 133 64 204"
							}
							"C12"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C12"
								"xpos"							"40"
								"ypos"							"20"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_12"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 140 64 255"
								"armedbgcolor_override"			"255 140 64 204"
							}
							"C13"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C13"
								"xpos"							"60"
								"ypos"							"20"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_13"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 146 64 255"
								"armedbgcolor_override"			"255 146 64 204"
							}
							"C14"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C14"
								"xpos"							"80"
								"ypos"							"20"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_14"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 153 64 255"
								"armedbgcolor_override"			"255 153 64 204"
							}
							"C15"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C15"
								"xpos"							"100"
								"ypos"							"20"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_15"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 159 64 255"
								"armedbgcolor_override"			"255 159 64 204"
							}
							"C16"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C16"
								"xpos"							"120"
								"ypos"							"20"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_16"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 165 64 255"
								"armedbgcolor_override"			"255 165 64 204"
							}
							"C17"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C17"
								"xpos"							"140"
								"ypos"							"20"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_17"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 172 64 255"
								"armedbgcolor_override"			"255 172 64 204"
							}
							"C18"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C18"
								"xpos"							"160"
								"ypos"							"20"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_18"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 178 64 255"
								"armedbgcolor_override"			"255 178 64 204"
							}
							"C19"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C19"
								"xpos"							"180"
								"ypos"							"20"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_19"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 184 64 255"
								"armedbgcolor_override"			"255 184 64 204"
							}
							"C20"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C20"
								"xpos"							"0"
								"ypos"							"40"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_20"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 191 64 255"
								"armedbgcolor_override"			"255 191 64 204"
							}
							"C21"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C21"
								"xpos"							"20"
								"ypos"							"40"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_21"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 197 64 255"
								"armedbgcolor_override"			"255 197 64 204"
							}
							"C22"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C22"
								"xpos"							"40"
								"ypos"							"40"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_22"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 203 64 255"
								"armedbgcolor_override"			"255 203 64 204"
							}
							"C23"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C23"
								"xpos"							"60"
								"ypos"							"40"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_23"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 210 64 255"
								"armedbgcolor_override"			"255 210 64 204"
							}
							"C24"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C24"
								"xpos"							"80"
								"ypos"							"40"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_24"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 216 64 255"
								"armedbgcolor_override"			"255 216 64 204"
							}
							"C25"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C25"
								"xpos"							"100"
								"ypos"							"40"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_25"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 222 64 255"
								"armedbgcolor_override"			"255 222 64 204"
							}
							"C26"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C26"
								"xpos"							"120"
								"ypos"							"40"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_26"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 229 64 255"
								"armedbgcolor_override"			"255 229 64 204"
							}
							"C27"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C27"
								"xpos"							"140"
								"ypos"							"40"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_27"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 235 64 255"
								"armedbgcolor_override"			"255 235 64 204"
							}
							"C28"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C28"
								"xpos"							"160"
								"ypos"							"40"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_28"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 241 64 255"
								"armedbgcolor_override"			"255 241 64 204"
							}
							"C29"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C29"
								"xpos"							"180"
								"ypos"							"40"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_29"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 248 64 255"
								"armedbgcolor_override"			"255 248 64 204"
							}
							"C30"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C30"
								"xpos"							"0"
								"ypos"							"60"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_30"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 254 64 255"
								"armedbgcolor_override"			"255 254 64 204"
							}
							"C31"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C31"
								"xpos"							"20"
								"ypos"							"60"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_31"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"250 255 64 255"
								"armedbgcolor_override"			"250 255 64 204"
							}
							"C32"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C32"
								"xpos"							"40"
								"ypos"							"60"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_32"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"243 255 64 255"
								"armedbgcolor_override"			"243 255 64 204"
							}
							"C33"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C33"
								"xpos"							"60"
								"ypos"							"60"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_33"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"237 255 64 255"
								"armedbgcolor_override"			"237 255 64 204"
							}
							"C34"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C34"
								"xpos"							"80"
								"ypos"							"60"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_34"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"231 255 64 255"
								"armedbgcolor_override"			"231 255 64 204"
							}
							"C35"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C35"
								"xpos"							"100"
								"ypos"							"60"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_35"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"224 255 64 255"
								"armedbgcolor_override"			"224 255 64 204"
							}
							"C36"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C36"
								"xpos"							"120"
								"ypos"							"60"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_36"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"218 255 64 255"
								"armedbgcolor_override"			"218 255 64 204"
							}
							"C37"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C37"
								"xpos"							"140"
								"ypos"							"60"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_37"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"212 255 64 255"
								"armedbgcolor_override"			"212 255 64 204"
							}
							"C38"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C38"
								"xpos"							"160"
								"ypos"							"60"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_38"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"205 255 64 255"
								"armedbgcolor_override"			"205 255 64 204"
							}
							"C39"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C39"
								"xpos"							"180"
								"ypos"							"60"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_39"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"199 255 64 255"
								"armedbgcolor_override"			"199 255 64 204"
							}
							"C40"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C40"
								"xpos"							"0"
								"ypos"							"80"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_40"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"193 255 64 255"
								"armedbgcolor_override"			"193 255 64 204"
							}
							"C41"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C41"
								"xpos"							"20"
								"ypos"							"80"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_41"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"186 255 64 255"
								"armedbgcolor_override"			"186 255 64 204"
							}
							"C42"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C42"
								"xpos"							"40"
								"ypos"							"80"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_42"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"180 255 64 255"
								"armedbgcolor_override"			"180 255 64 204"
							}
							"C43"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C43"
								"xpos"							"60"
								"ypos"							"80"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_43"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"174 255 64 255"
								"armedbgcolor_override"			"174 255 64 204"
							}
							"C44"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C44"
								"xpos"							"80"
								"ypos"							"80"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_44"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"167 255 64 255"
								"armedbgcolor_override"			"167 255 64 204"
							}
							"C45"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C45"
								"xpos"							"100"
								"ypos"							"80"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_45"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"161 255 64 255"
								"armedbgcolor_override"			"161 255 64 204"
							}
							"C46"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C46"
								"xpos"							"120"
								"ypos"							"80"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_46"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"155 255 64 255"
								"armedbgcolor_override"			"155 255 64 204"
							}
							"C47"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C47"
								"xpos"							"140"
								"ypos"							"80"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_47"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"148 255 64 255"
								"armedbgcolor_override"			"148 255 64 204"
							}
							"C48"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C48"
								"xpos"							"160"
								"ypos"							"80"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_48"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"142 255 64 255"
								"armedbgcolor_override"			"142 255 64 204"
							}
							"C49"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C49"
								"xpos"							"180"
								"ypos"							"80"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_49"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"136 255 64 255"
								"armedbgcolor_override"			"136 255 64 204"
							}
							"C50"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C50"
								"xpos"							"0"
								"ypos"							"100"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_50"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"129 255 64 255"
								"armedbgcolor_override"			"129 255 64 204"
							}
							"C51"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C51"
								"xpos"							"20"
								"ypos"							"100"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_51"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"123 255 64 255"
								"armedbgcolor_override"			"123 255 64 204"
							}
							"C52"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C52"
								"xpos"							"40"
								"ypos"							"100"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_52"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"117 255 64 255"
								"armedbgcolor_override"			"117 255 64 204"
							}
							"C53"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C53"
								"xpos"							"60"
								"ypos"							"100"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_53"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"110 255 64 255"
								"armedbgcolor_override"			"110 255 64 204"
							}
							"C54"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C54"
								"xpos"							"80"
								"ypos"							"100"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_54"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"104 255 64 255"
								"armedbgcolor_override"			"104 255 64 204"
							}
							"C55"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C55"
								"xpos"							"100"
								"ypos"							"100"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_55"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"98 255 64 255"
								"armedbgcolor_override"			"98 255 64 204"
							}
							"C56"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C56"
								"xpos"							"120"
								"ypos"							"100"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_56"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"91 255 64 255"
								"armedbgcolor_override"			"91 255 64 204"
							}
							"C57"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C57"
								"xpos"							"140"
								"ypos"							"100"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_57"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"85 255 64 255"
								"armedbgcolor_override"			"85 255 64 204"
							}
							"C58"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C58"
								"xpos"							"160"
								"ypos"							"100"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_58"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"79 255 64 255"
								"armedbgcolor_override"			"79 255 64 204"
							}
							"C59"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C59"
								"xpos"							"180"
								"ypos"							"100"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_59"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"72 255 64 255"
								"armedbgcolor_override"			"72 255 64 204"
							}
							"C60"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C60"
								"xpos"							"0"
								"ypos"							"120"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_60"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"66 255 64 255"
								"armedbgcolor_override"			"66 255 64 204"
							}
							"C61"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C61"
								"xpos"							"20"
								"ypos"							"120"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_61"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 68 255"
								"armedbgcolor_override"			"64 255 68 204"
							}
							"C62"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C62"
								"xpos"							"40"
								"ypos"							"120"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_62"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 74 255"
								"armedbgcolor_override"			"64 255 74 204"
							}
							"C63"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C63"
								"xpos"							"60"
								"ypos"							"120"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_63"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 81 255"
								"armedbgcolor_override"			"64 255 81 204"
							}
							"C64"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C64"
								"xpos"							"80"
								"ypos"							"120"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_64"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 87 255"
								"armedbgcolor_override"			"64 255 87 204"
							}
							"C65"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C65"
								"xpos"							"100"
								"ypos"							"120"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_65"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 93 255"
								"armedbgcolor_override"			"64 255 93 204"
							}
							"C66"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C66"
								"xpos"							"120"
								"ypos"							"120"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_66"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 100 255"
								"armedbgcolor_override"			"64 255 100 204"
							}
							"C67"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C67"
								"xpos"							"140"
								"ypos"							"120"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_67"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 106 255"
								"armedbgcolor_override"			"64 255 106 204"
							}
							"C68"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C68"
								"xpos"							"160"
								"ypos"							"120"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_68"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 112 255"
								"armedbgcolor_override"			"64 255 112 204"
							}
							"C69"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C69"
								"xpos"							"180"
								"ypos"							"120"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_69"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 119 255"
								"armedbgcolor_override"			"64 255 119 204"
							}
							"C70"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C70"
								"xpos"							"0"
								"ypos"							"140"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_70"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 125 255"
								"armedbgcolor_override"			"64 255 125 204"
							}
							"C71"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C71"
								"xpos"							"20"
								"ypos"							"140"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_71"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 131 255"
								"armedbgcolor_override"			"64 255 131 204"
							}
							"C72"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C72"
								"xpos"							"40"
								"ypos"							"140"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_72"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 138 255"
								"armedbgcolor_override"			"64 255 138 204"
							}
							"C73"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C73"
								"xpos"							"60"
								"ypos"							"140"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_73"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 144 255"
								"armedbgcolor_override"			"64 255 144 204"
							}
							"C74"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C74"
								"xpos"							"80"
								"ypos"							"140"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_74"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 150 255"
								"armedbgcolor_override"			"64 255 150 204"
							}
							"C75"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C75"
								"xpos"							"100"
								"ypos"							"140"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_75"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 157 255"
								"armedbgcolor_override"			"64 255 157 204"
							}
							"C76"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C76"
								"xpos"							"120"
								"ypos"							"140"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_76"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 163 255"
								"armedbgcolor_override"			"64 255 163 204"
							}
							"C77"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C77"
								"xpos"							"140"
								"ypos"							"140"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_77"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 169 255"
								"armedbgcolor_override"			"64 255 169 204"
							}
							"C78"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C78"
								"xpos"							"160"
								"ypos"							"140"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_78"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 176 255"
								"armedbgcolor_override"			"64 255 176 204"
							}
							"C79"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C79"
								"xpos"							"180"
								"ypos"							"140"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_79"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 182 255"
								"armedbgcolor_override"			"64 255 182 204"
							}
							"C80"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C80"
								"xpos"							"0"
								"ypos"							"160"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_80"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 188 255"
								"armedbgcolor_override"			"64 255 188 204"
							}
							"C81"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C81"
								"xpos"							"20"
								"ypos"							"160"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_81"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 195 255"
								"armedbgcolor_override"			"64 255 195 204"
							}
							"C82"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C82"
								"xpos"							"40"
								"ypos"							"160"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_82"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 201 255"
								"armedbgcolor_override"			"64 255 201 204"
							}
							"C83"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C83"
								"xpos"							"60"
								"ypos"							"160"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_83"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 207 255"
								"armedbgcolor_override"			"64 255 207 204"
							}
							"C84"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C84"
								"xpos"							"80"
								"ypos"							"160"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_84"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 214 255"
								"armedbgcolor_override"			"64 255 214 204"
							}
							"C85"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C85"
								"xpos"							"100"
								"ypos"							"160"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_85"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 220 255"
								"armedbgcolor_override"			"64 255 220 204"
							}
							"C86"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C86"
								"xpos"							"120"
								"ypos"							"160"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_86"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 226 255"
								"armedbgcolor_override"			"64 255 226 204"
							}
							"C87"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C87"
								"xpos"							"140"
								"ypos"							"160"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_87"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 233 255"
								"armedbgcolor_override"			"64 255 233 204"
							}
							"C88"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C88"
								"xpos"							"160"
								"ypos"							"160"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_88"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 239 255"
								"armedbgcolor_override"			"64 255 239 204"
							}
							"C89"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C89"
								"xpos"							"180"
								"ypos"							"160"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_89"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 245 255"
								"armedbgcolor_override"			"64 255 245 204"
							}
							"C90"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C90"
								"xpos"							"0"
								"ypos"							"180"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_90"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 255 252 255"
								"armedbgcolor_override"			"64 255 252 204"
							}
							"C91"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C91"
								"xpos"							"20"
								"ypos"							"180"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_91"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 252 255 255"
								"armedbgcolor_override"			"64 252 255 204"
							}
							"C92"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C92"
								"xpos"							"40"
								"ypos"							"180"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_92"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 245 255 255"
								"armedbgcolor_override"			"64 245 255 204"
							}
							"C93"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C93"
								"xpos"							"60"
								"ypos"							"180"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_93"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 239 255 255"
								"armedbgcolor_override"			"64 239 255 204"
							}
							"C94"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C94"
								"xpos"							"80"
								"ypos"							"180"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_94"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 233 255 255"
								"armedbgcolor_override"			"64 233 255 204"
							}
							"C95"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C95"
								"xpos"							"100"
								"ypos"							"180"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_95"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 226 255 255"
								"armedbgcolor_override"			"64 226 255 204"
							}
							"C96"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C96"
								"xpos"							"120"
								"ypos"							"180"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_96"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 220 255 255"
								"armedbgcolor_override"			"64 220 255 204"
							}
							"C97"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C97"
								"xpos"							"140"
								"ypos"							"180"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_97"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 214 255 255"
								"armedbgcolor_override"			"64 214 255 204"
							}
							"C98"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C98"
								"xpos"							"160"
								"ypos"							"180"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_98"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 207 255 255"
								"armedbgcolor_override"			"64 207 255 204"
							}
							"C99"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C99"
								"xpos"							"180"
								"ypos"							"180"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_99"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 201 255 255"
								"armedbgcolor_override"			"64 201 255 204"
							}
							"C100"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C100"
								"xpos"							"0"
								"ypos"							"200"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_100"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 195 255 255"
								"armedbgcolor_override"			"64 195 255 204"
							}
							"C101"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C101"
								"xpos"							"20"
								"ypos"							"200"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_101"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 188 255 255"
								"armedbgcolor_override"			"64 188 255 204"
							}
							"C102"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C102"
								"xpos"							"40"
								"ypos"							"200"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_102"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 182 255 255"
								"armedbgcolor_override"			"64 182 255 204"
							}
							"C103"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C103"
								"xpos"							"60"
								"ypos"							"200"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_103"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 176 255 255"
								"armedbgcolor_override"			"64 176 255 204"
							}
							"C104"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C104"
								"xpos"							"80"
								"ypos"							"200"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_104"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 169 255 255"
								"armedbgcolor_override"			"64 169 255 204"
							}
							"C105"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C105"
								"xpos"							"100"
								"ypos"							"200"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_105"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 163 255 255"
								"armedbgcolor_override"			"64 163 255 204"
							}
							"C106"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C106"
								"xpos"							"120"
								"ypos"							"200"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_106"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 157 255 255"
								"armedbgcolor_override"			"64 157 255 204"
							}
							"C107"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C107"
								"xpos"							"140"
								"ypos"							"200"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_107"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 150 255 255"
								"armedbgcolor_override"			"64 150 255 204"
							}
							"C108"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C108"
								"xpos"							"160"
								"ypos"							"200"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_108"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 144 255 255"
								"armedbgcolor_override"			"64 144 255 204"
							}
							"C109"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C109"
								"xpos"							"180"
								"ypos"							"200"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_109"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 138 255 255"
								"armedbgcolor_override"			"64 138 255 204"
							}
							"C110"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C110"
								"xpos"							"0"
								"ypos"							"220"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_110"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 131 255 255"
								"armedbgcolor_override"			"64 131 255 204"
							}
							"C111"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C111"
								"xpos"							"20"
								"ypos"							"220"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_111"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 125 255 255"
								"armedbgcolor_override"			"64 125 255 204"
							}
							"C112"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C112"
								"xpos"							"40"
								"ypos"							"220"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_112"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 119 255 255"
								"armedbgcolor_override"			"64 119 255 204"
							}
							"C113"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C113"
								"xpos"							"60"
								"ypos"							"220"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_113"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 112 255 255"
								"armedbgcolor_override"			"64 112 255 204"
							}
							"C114"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C114"
								"xpos"							"80"
								"ypos"							"220"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_114"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 106 255 255"
								"armedbgcolor_override"			"64 106 255 204"
							}
							"C115"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C115"
								"xpos"							"100"
								"ypos"							"220"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_115"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 100 255 255"
								"armedbgcolor_override"			"64 100 255 204"
							}
							"C116"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C116"
								"xpos"							"120"
								"ypos"							"220"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_116"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 93 255 255"
								"armedbgcolor_override"			"64 93 255 204"
							}
							"C117"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C117"
								"xpos"							"140"
								"ypos"							"220"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_117"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 87 255 255"
								"armedbgcolor_override"			"64 87 255 204"
							}
							"C118"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C118"
								"xpos"							"160"
								"ypos"							"220"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_118"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 81 255 255"
								"armedbgcolor_override"			"64 81 255 204"
							}
							"C119"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C119"
								"xpos"							"180"
								"ypos"							"220"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_119"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 74 255 255"
								"armedbgcolor_override"			"64 74 255 204"
							}
							"C120"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C120"
								"xpos"							"0"
								"ypos"							"240"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_120"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"64 68 255 255"
								"armedbgcolor_override"			"64 68 255 204"
							}
							"C121"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C121"
								"xpos"							"20"
								"ypos"							"240"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_121"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"66 64 255 255"
								"armedbgcolor_override"			"66 64 255 204"
							}
							"C122"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C122"
								"xpos"							"40"
								"ypos"							"240"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_122"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"72 64 255 255"
								"armedbgcolor_override"			"72 64 255 204"
							}
							"C123"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C123"
								"xpos"							"60"
								"ypos"							"240"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_123"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"79 64 255 255"
								"armedbgcolor_override"			"79 64 255 204"
							}
							"C124"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C124"
								"xpos"							"80"
								"ypos"							"240"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_124"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"85 64 255 255"
								"armedbgcolor_override"			"85 64 255 204"
							}
							"C125"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C125"
								"xpos"							"100"
								"ypos"							"240"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_125"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"91 64 255 255"
								"armedbgcolor_override"			"91 64 255 204"
							}
							"C126"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C126"
								"xpos"							"120"
								"ypos"							"240"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_126"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"98 64 255 255"
								"armedbgcolor_override"			"98 64 255 204"
							}
							"C127"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C127"
								"xpos"							"140"
								"ypos"							"240"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_127"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"104 64 255 255"
								"armedbgcolor_override"			"104 64 255 204"
							}
							"C128"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C128"
								"xpos"							"160"
								"ypos"							"240"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_128"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"110 64 255 255"
								"armedbgcolor_override"			"110 64 255 204"
							}
							"C129"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C129"
								"xpos"							"180"
								"ypos"							"240"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_129"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"117 64 255 255"
								"armedbgcolor_override"			"117 64 255 204"
							}
							"C130"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C130"
								"xpos"							"0"
								"ypos"							"260"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_130"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"123 64 255 255"
								"armedbgcolor_override"			"123 64 255 204"
							}
							"C131"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C131"
								"xpos"							"20"
								"ypos"							"260"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_131"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"129 64 255 255"
								"armedbgcolor_override"			"129 64 255 204"
							}
							"C132"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C132"
								"xpos"							"40"
								"ypos"							"260"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_132"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"136 64 255 255"
								"armedbgcolor_override"			"136 64 255 204"
							}
							"C133"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C133"
								"xpos"							"60"
								"ypos"							"260"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_133"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"142 64 255 255"
								"armedbgcolor_override"			"142 64 255 204"
							}
							"C134"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C134"
								"xpos"							"80"
								"ypos"							"260"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_134"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"148 64 255 255"
								"armedbgcolor_override"			"148 64 255 204"
							}
							"C135"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C135"
								"xpos"							"100"
								"ypos"							"260"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_135"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"155 64 255 255"
								"armedbgcolor_override"			"155 64 255 204"
							}
							"C136"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C136"
								"xpos"							"120"
								"ypos"							"260"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_136"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"161 64 255 255"
								"armedbgcolor_override"			"161 64 255 204"
							}
							"C137"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C137"
								"xpos"							"140"
								"ypos"							"260"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_137"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"167 64 255 255"
								"armedbgcolor_override"			"167 64 255 204"
							}
							"C138"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C138"
								"xpos"							"160"
								"ypos"							"260"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_138"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"174 64 255 255"
								"armedbgcolor_override"			"174 64 255 204"
							}
							"C139"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C139"
								"xpos"							"180"
								"ypos"							"260"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_139"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"180 64 255 255"
								"armedbgcolor_override"			"180 64 255 204"
							}
							"C140"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C140"
								"xpos"							"0"
								"ypos"							"280"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_140"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"186 64 255 255"
								"armedbgcolor_override"			"186 64 255 204"
							}
							"C141"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C141"
								"xpos"							"20"
								"ypos"							"280"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_141"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"193 64 255 255"
								"armedbgcolor_override"			"193 64 255 204"
							}
							"C142"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C142"
								"xpos"							"40"
								"ypos"							"280"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_142"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"199 64 255 255"
								"armedbgcolor_override"			"199 64 255 204"
							}
							"C143"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C143"
								"xpos"							"60"
								"ypos"							"280"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_143"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"205 64 255 255"
								"armedbgcolor_override"			"205 64 255 204"
							}
							"C144"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C144"
								"xpos"							"80"
								"ypos"							"280"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_144"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"212 64 255 255"
								"armedbgcolor_override"			"212 64 255 204"
							}
							"C145"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C145"
								"xpos"							"100"
								"ypos"							"280"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_145"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"218 64 255 255"
								"armedbgcolor_override"			"218 64 255 204"
							}
							"C146"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C146"
								"xpos"							"120"
								"ypos"							"280"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_146"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"224 64 255 255"
								"armedbgcolor_override"			"224 64 255 204"
							}
							"C147"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C147"
								"xpos"							"140"
								"ypos"							"280"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_147"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"231 64 255 255"
								"armedbgcolor_override"			"231 64 255 204"
							}
							"C148"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C148"
								"xpos"							"160"
								"ypos"							"280"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_148"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"237 64 255 255"
								"armedbgcolor_override"			"237 64 255 204"
							}
							"C149"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C149"
								"xpos"							"180"
								"ypos"							"280"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_149"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"243 64 255 255"
								"armedbgcolor_override"			"243 64 255 204"
							}
							"C150"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C150"
								"xpos"							"0"
								"ypos"							"300"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_150"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"250 64 255 255"
								"armedbgcolor_override"			"250 64 255 204"
							}
							"C151"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C151"
								"xpos"							"20"
								"ypos"							"300"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_151"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 254 255"
								"armedbgcolor_override"			"255 64 254 204"
							}
							"C152"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C152"
								"xpos"							"40"
								"ypos"							"300"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_152"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 248 255"
								"armedbgcolor_override"			"255 64 248 204"
							}
							"C153"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C153"
								"xpos"							"60"
								"ypos"							"300"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_153"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 241 255"
								"armedbgcolor_override"			"255 64 241 204"
							}
							"C154"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C154"
								"xpos"							"80"
								"ypos"							"300"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_154"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 235 255"
								"armedbgcolor_override"			"255 64 235 204"
							}
							"C155"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C155"
								"xpos"							"100"
								"ypos"							"300"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_155"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 229 255"
								"armedbgcolor_override"			"255 64 229 204"
							}
							"C156"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C156"
								"xpos"							"120"
								"ypos"							"300"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_156"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 222 255"
								"armedbgcolor_override"			"255 64 222 204"
							}
							"C157"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C157"
								"xpos"							"140"
								"ypos"							"300"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_157"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 216 255"
								"armedbgcolor_override"			"255 64 216 204"
							}
							"C158"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C158"
								"xpos"							"160"
								"ypos"							"300"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_158"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 210 255"
								"armedbgcolor_override"			"255 64 210 204"
							}
							"C159"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C159"
								"xpos"							"180"
								"ypos"							"300"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_159"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 203 255"
								"armedbgcolor_override"			"255 64 203 204"
							}
							"C160"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C160"
								"xpos"							"0"
								"ypos"							"320"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_160"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 197 255"
								"armedbgcolor_override"			"255 64 197 204"
							}
							"C161"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C161"
								"xpos"							"20"
								"ypos"							"320"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_161"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 191 255"
								"armedbgcolor_override"			"255 64 191 204"
							}
							"C162"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C162"
								"xpos"							"40"
								"ypos"							"320"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_162"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 184 255"
								"armedbgcolor_override"			"255 64 184 204"
							}
							"C163"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C163"
								"xpos"							"60"
								"ypos"							"320"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_163"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 178 255"
								"armedbgcolor_override"			"255 64 178 204"
							}
							"C164"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C164"
								"xpos"							"80"
								"ypos"							"320"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_164"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 172 255"
								"armedbgcolor_override"			"255 64 172 204"
							}
							"C165"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C165"
								"xpos"							"100"
								"ypos"							"320"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_165"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 165 255"
								"armedbgcolor_override"			"255 64 165 204"
							}
							"C166"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C166"
								"xpos"							"120"
								"ypos"							"320"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_166"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 159 255"
								"armedbgcolor_override"			"255 64 159 204"
							}
							"C167"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C167"
								"xpos"							"140"
								"ypos"							"320"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_167"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 153 255"
								"armedbgcolor_override"			"255 64 153 204"
							}
							"C168"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C168"
								"xpos"							"160"
								"ypos"							"320"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_168"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 146 255"
								"armedbgcolor_override"			"255 64 146 204"
							}
							"C169"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C169"
								"xpos"							"180"
								"ypos"							"320"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_169"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 140 255"
								"armedbgcolor_override"			"255 64 140 204"
							}
							"C170"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C170"
								"xpos"							"0"
								"ypos"							"340"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_170"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 133 255"
								"armedbgcolor_override"			"255 64 133 204"
							}
							"C171"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C171"
								"xpos"							"20"
								"ypos"							"340"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_171"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 127 255"
								"armedbgcolor_override"			"255 64 127 204"
							}
							"C172"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C172"
								"xpos"							"40"
								"ypos"							"340"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_172"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 121 255"
								"armedbgcolor_override"			"255 64 121 204"
							}
							"C173"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C173"
								"xpos"							"60"
								"ypos"							"340"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_173"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 114 255"
								"armedbgcolor_override"			"255 64 114 204"
							}
							"C174"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C174"
								"xpos"							"80"
								"ypos"							"340"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_174"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 108 255"
								"armedbgcolor_override"			"255 64 108 204"
							}
							"C175"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C175"
								"xpos"							"100"
								"ypos"							"340"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_175"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 102 255"
								"armedbgcolor_override"			"255 64 102 204"
							}
							"C176"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C176"
								"xpos"							"120"
								"ypos"							"340"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_176"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 95 255"
								"armedbgcolor_override"			"255 64 95 204"
							}
							"C177"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C177"
								"xpos"							"140"
								"ypos"							"340"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_177"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 89 255"
								"armedbgcolor_override"			"255 64 89 204"
							}
							"C178"
							{
								"ControlName"					"CExButton"
								"fieldName"						"C178"
								"xpos"							"160"
								"ypos"							"340"
								"wide"							"20"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"labeltext"						""
								"paintbackground"				"1"
								"command"						"engine ih_accent_178"
								"actionsignallevel"				"6"
								"defaultbgcolor_override"		"255 64 83 255"
								"armedbgcolor_override"			"255 64 83 204"
							}
						}
					}
				}
			}
		}
	}
}
