"Resource/UI/MainMenuOverride.res"
{
	"MainMenuOverride"
	{
		"CustomizationMenu"
		{
			"MainPanel"
			{
				"SectionContainer"
				{
					"Crosshairs"
					{
						"Buttons"
						{
							"CrosshairShape0"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape0"
								"xpos"						"0"
								"ypos"						"0"
								"command"					"engine ih_crosshair_shape_0"
								"labelText"					"!"
							}
							"CrosshairShape1"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape1"
								"xpos"						"20"
								"ypos"						"0"
								"command"					"engine ih_crosshair_shape_1"
								"labelText"					"#"
							}
							"CrosshairShape2"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape2"
								"xpos"						"40"
								"ypos"						"0"
								"command"					"engine ih_crosshair_shape_2"
								"labelText"					"$"
							}
							"CrosshairShape3"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape3"
								"xpos"						"60"
								"ypos"						"0"
								"command"					"engine ih_crosshair_shape_3"
								"labelText"					"%"
							}
							"CrosshairShape4"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape4"
								"xpos"						"80"
								"ypos"						"0"
								"command"					"engine ih_crosshair_shape_4"
								"labelText"					"'"
							}
							"CrosshairShape5"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape5"
								"xpos"						"100"
								"ypos"						"0"
								"command"					"engine ih_crosshair_shape_5"
								"labelText"					"("
							}
							"CrosshairShape6"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape6"
								"xpos"						"120"
								"ypos"						"0"
								"command"					"engine ih_crosshair_shape_6"
								"labelText"					")"
							}
							"CrosshairShape7"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape7"
								"xpos"						"140"
								"ypos"						"0"
								"command"					"engine ih_crosshair_shape_7"
								"labelText"					"*"
							}
							"CrosshairShape8"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape8"
								"xpos"						"160"
								"ypos"						"0"
								"command"					"engine ih_crosshair_shape_8"
								"labelText"					"+"
							}
							"CrosshairShape9"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape9"
								"xpos"						"180"
								"ypos"						"0"
								"command"					"engine ih_crosshair_shape_9"
								"labelText"					","
							}
							"CrosshairShape10"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape10"
								"xpos"						"0"
								"ypos"						"20"
								"command"					"engine ih_crosshair_shape_10"
								"labelText"					"-"
							}
							"CrosshairShape11"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape11"
								"xpos"						"20"
								"ypos"						"20"
								"command"					"engine ih_crosshair_shape_11"
								"labelText"					"."
							}
							"CrosshairShape12"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape12"
								"xpos"						"40"
								"ypos"						"20"
								"command"					"engine ih_crosshair_shape_12"
								"labelText"					"/"
							}
							"CrosshairShape13"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape13"
								"xpos"						"60"
								"ypos"						"20"
								"command"					"engine ih_crosshair_shape_13"
								"labelText"					"0"
							}
							"CrosshairShape14"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape14"
								"xpos"						"80"
								"ypos"						"20"
								"command"					"engine ih_crosshair_shape_14"
								"labelText"					"1"
							}
							"CrosshairShape15"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape15"
								"xpos"						"100"
								"ypos"						"20"
								"command"					"engine ih_crosshair_shape_15"
								"labelText"					"2"
							}
							"CrosshairShape16"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape16"
								"xpos"						"120"
								"ypos"						"20"
								"command"					"engine ih_crosshair_shape_16"
								"labelText"					"3"
							}
							"CrosshairShape17"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape17"
								"xpos"						"140"
								"ypos"						"20"
								"command"					"engine ih_crosshair_shape_17"
								"labelText"					"4"
							}
							"CrosshairShape18"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape18"
								"xpos"						"160"
								"ypos"						"20"
								"command"					"engine ih_crosshair_shape_18"
								"labelText"					"5"
							}
							"CrosshairShape19"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape19"
								"xpos"						"180"
								"ypos"						"20"
								"command"					"engine ih_crosshair_shape_19"
								"labelText"					"6"
							}
							"CrosshairShape20"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape20"
								"xpos"						"0"
								"ypos"						"40"
								"command"					"engine ih_crosshair_shape_20"
								"labelText"					"7"
							}
							"CrosshairShape21"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape21"
								"xpos"						"20"
								"ypos"						"40"
								"command"					"engine ih_crosshair_shape_21"
								"labelText"					"8"
							}
							"CrosshairShape22"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape22"
								"xpos"						"40"
								"ypos"						"40"
								"command"					"engine ih_crosshair_shape_22"
								"labelText"					"9"
							}
							"CrosshairShape23"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape23"
								"xpos"						"60"
								"ypos"						"40"
								"command"					"engine ih_crosshair_shape_23"
								"labelText"					":"
							}
							"CrosshairShape24"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_1"
								"border_armed"				"FLAT_Black_1"
								"defaultFgColor_override"	"TextT4"
								"armedfgcolor_override"		"TextT4"
								"fieldName"					"CrosshairShape24"
								"xpos"						"80"
								"ypos"						"40"
								"command"					"engine clear; showconsole; echo Disabled temporarily due to a bug."
								"labelText"					";"
							}
							"CrosshairShape25"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape25"
								"xpos"						"100"
								"ypos"						"40"
								"command"					"engine ih_crosshair_shape_25"
								"labelText"					"<"
							}
							"CrosshairShape26"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape26"
								"xpos"						"120"
								"ypos"						"40"
								"command"					"engine ih_crosshair_shape_26"
								"labelText"					"="
							}
							"CrosshairShape27"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape27"
								"xpos"						"140"
								"ypos"						"40"
								"command"					"engine ih_crosshair_shape_27"
								"labelText"					">"
							}
							"CrosshairShape28"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape28"
								"xpos"						"160"
								"ypos"						"40"
								"command"					"engine ih_crosshair_shape_28"
								"labelText"					"?"
							}
							"CrosshairShape29"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape29"
								"xpos"						"180"
								"ypos"						"40"
								"command"					"engine ih_crosshair_shape_29"
								"labelText"					"@"
							}
							"CrosshairShape30"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape30"
								"xpos"						"0"
								"ypos"						"60"
								"command"					"engine ih_crosshair_shape_30"
								"labelText"					"A"
							}
							"CrosshairShape31"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape31"
								"xpos"						"20"
								"ypos"						"60"
								"command"					"engine ih_crosshair_shape_31"
								"labelText"					"B"
							}
							"CrosshairShape32"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape32"
								"xpos"						"40"
								"ypos"						"60"
								"command"					"engine ih_crosshair_shape_32"
								"labelText"					"C"
							}
							"CrosshairShape33"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape33"
								"xpos"						"60"
								"ypos"						"60"
								"command"					"engine ih_crosshair_shape_33"
								"labelText"					"D"
							}
							"CrosshairShape34"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape34"
								"xpos"						"80"
								"ypos"						"60"
								"command"					"engine ih_crosshair_shape_34"
								"labelText"					"E"
							}
							"CrosshairShape35"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape35"
								"xpos"						"100"
								"ypos"						"60"
								"command"					"engine ih_crosshair_shape_35"
								"labelText"					"F"
							}
							"CrosshairShape36"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape36"
								"xpos"						"120"
								"ypos"						"60"
								"command"					"engine ih_crosshair_shape_36"
								"labelText"					"G"
							}
							"CrosshairShape37"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape37"
								"xpos"						"140"
								"ypos"						"60"
								"command"					"engine ih_crosshair_shape_37"
								"labelText"					"H"
							}
							"CrosshairShape38"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape38"
								"xpos"						"160"
								"ypos"						"60"
								"command"					"engine ih_crosshair_shape_38"
								"labelText"					"I"
							}
							"CrosshairShape39"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape39"
								"xpos"						"180"
								"ypos"						"60"
								"command"					"engine ih_crosshair_shape_39"
								"labelText"					"J"
							}
							"CrosshairShape40"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape40"
								"xpos"						"0"
								"ypos"						"80"
								"command"					"engine ih_crosshair_shape_40"
								"labelText"					"K"
							}
							"CrosshairShape41"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape41"
								"xpos"						"20"
								"ypos"						"80"
								"command"					"engine ih_crosshair_shape_41"
								"labelText"					"L"
							}
							"CrosshairShape42"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape42"
								"xpos"						"40"
								"ypos"						"80"
								"command"					"engine ih_crosshair_shape_42"
								"labelText"					"M"
							}
							"CrosshairShape43"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape43"
								"xpos"						"60"
								"ypos"						"80"
								"command"					"engine ih_crosshair_shape_43"
								"labelText"					"N"
							}
							"CrosshairShape44"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape44"
								"xpos"						"80"
								"ypos"						"80"
								"command"					"engine ih_crosshair_shape_44"
								"labelText"					"O"
							}
							"CrosshairShape45"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape45"
								"xpos"						"100"
								"ypos"						"80"
								"command"					"engine ih_crosshair_shape_45"
								"labelText"					"P"
							}
							"CrosshairShape46"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape46"
								"xpos"						"120"
								"ypos"						"80"
								"command"					"engine ih_crosshair_shape_46"
								"labelText"					"Q"
							}
							"CrosshairShape47"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape47"
								"xpos"						"140"
								"ypos"						"80"
								"command"					"engine ih_crosshair_shape_47"
								"labelText"					"R"
							}
							"CrosshairShape48"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape48"
								"xpos"						"160"
								"ypos"						"80"
								"command"					"engine ih_crosshair_shape_48"
								"labelText"					"S"
							}
							"CrosshairShape49"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape49"
								"xpos"						"180"
								"ypos"						"80"
								"command"					"engine ih_crosshair_shape_49"
								"labelText"					"T"
							}
							"CrosshairShape50"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape50"
								"xpos"						"0"
								"ypos"						"100"
								"command"					"engine ih_crosshair_shape_50"
								"labelText"					"U"
							}
							"CrosshairShape51"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape51"
								"xpos"						"20"
								"ypos"						"100"
								"command"					"engine ih_crosshair_shape_51"
								"labelText"					"V"
							}
							"CrosshairShape52"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape52"
								"xpos"						"40"
								"ypos"						"100"
								"command"					"engine ih_crosshair_shape_52"
								"labelText"					"W"
							}
							"CrosshairShape53"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape53"
								"xpos"						"60"
								"ypos"						"100"
								"command"					"engine ih_crosshair_shape_53"
								"labelText"					"X"
							}
							"CrosshairShape54"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape54"
								"xpos"						"80"
								"ypos"						"100"
								"command"					"engine ih_crosshair_shape_54"
								"labelText"					"Y"
							}
							"CrosshairShape55"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape55"
								"xpos"						"100"
								"ypos"						"100"
								"command"					"engine ih_crosshair_shape_55"
								"labelText"					"Z"
							}
							"CrosshairShape56"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape56"
								"xpos"						"120"
								"ypos"						"100"
								"command"					"engine ih_crosshair_shape_56"
								"labelText"					"["
							}
							"CrosshairShape57"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape57"
								"xpos"						"140"
								"ypos"						"100"
								"command"					"engine ih_crosshair_shape_57"
								"labelText"					"\"
							}
							"CrosshairShape58"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape58"
								"xpos"						"160"
								"ypos"						"100"
								"command"					"engine ih_crosshair_shape_58"
								"labelText"					"]"
							}
							"CrosshairShape59"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape59"
								"xpos"						"180"
								"ypos"						"100"
								"command"					"engine ih_crosshair_shape_59"
								"labelText"					"^"
							}
							"CrosshairShape60"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape60"
								"xpos"						"0"
								"ypos"						"120"
								"command"					"engine ih_crosshair_shape_60"
								"labelText"					"_"
							}
							"CrosshairShape61"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape61"
								"xpos"						"20"
								"ypos"						"120"
								"command"					"engine ih_crosshair_shape_61"
								"labelText"					"`"
							}
							"CrosshairShape62"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape62"
								"xpos"						"40"
								"ypos"						"120"
								"command"					"engine ih_crosshair_shape_62"
								"labelText"					"a"
							}
							"CrosshairShape63"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape63"
								"xpos"						"60"
								"ypos"						"120"
								"command"					"engine ih_crosshair_shape_63"
								"labelText"					"b"
							}
							"CrosshairShape64"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape64"
								"xpos"						"80"
								"ypos"						"120"
								"command"					"engine ih_crosshair_shape_64"
								"labelText"					"c"
							}
							"CrosshairShape65"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape65"
								"xpos"						"100"
								"ypos"						"120"
								"command"					"engine ih_crosshair_shape_65"
								"labelText"					"d"
							}
							"CrosshairShape66"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape66"
								"xpos"						"120"
								"ypos"						"120"
								"command"					"engine ih_crosshair_shape_66"
								"labelText"					"e"
							}
							"CrosshairShape67"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape67"
								"xpos"						"140"
								"ypos"						"120"
								"command"					"engine ih_crosshair_shape_67"
								"labelText"					"f"
							}
							"CrosshairShape68"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape68"
								"xpos"						"160"
								"ypos"						"120"
								"command"					"engine ih_crosshair_shape_68"
								"labelText"					"g"
							}
							"CrosshairShape69"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape69"
								"xpos"						"180"
								"ypos"						"120"
								"command"					"engine ih_crosshair_shape_69"
								"labelText"					"h"
							}
							"CrosshairShape70"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape70"
								"xpos"						"0"
								"ypos"						"140"
								"command"					"engine ih_crosshair_shape_70"
								"labelText"					"i"
							}
							"CrosshairShape71"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape71"
								"xpos"						"20"
								"ypos"						"140"
								"command"					"engine ih_crosshair_shape_71"
								"labelText"					"j"
							}
							"CrosshairShape72"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape72"
								"xpos"						"40"
								"ypos"						"140"
								"command"					"engine ih_crosshair_shape_72"
								"labelText"					"k"
							}
							"CrosshairShape73"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape73"
								"xpos"						"60"
								"ypos"						"140"
								"command"					"engine ih_crosshair_shape_73"
								"labelText"					"l"
							}
							"CrosshairShape74"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape74"
								"xpos"						"80"
								"ypos"						"140"
								"command"					"engine ih_crosshair_shape_74"
								"labelText"					"m"
							}
							"CrosshairShape75"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape75"
								"xpos"						"100"
								"ypos"						"140"
								"command"					"engine ih_crosshair_shape_75"
								"labelText"					"n"
							}
							"CrosshairShape76"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape76"
								"xpos"						"120"
								"ypos"						"140"
								"command"					"engine ih_crosshair_shape_76"
								"labelText"					"o"
							}
							"CrosshairShape77"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape77"
								"xpos"						"140"
								"ypos"						"140"
								"command"					"engine ih_crosshair_shape_77"
								"labelText"					"p"
							}
							"CrosshairShape78"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape78"
								"xpos"						"160"
								"ypos"						"140"
								"command"					"engine ih_crosshair_shape_78"
								"labelText"					"q"
							}
							"CrosshairShape79"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape79"
								"xpos"						"180"
								"ypos"						"140"
								"command"					"engine ih_crosshair_shape_79"
								"labelText"					"r"
							}
							"CrosshairShape80"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape80"
								"xpos"						"0"
								"ypos"						"160"
								"command"					"engine ih_crosshair_shape_80"
								"labelText"					"s"
							}
							"CrosshairShape81"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape81"
								"xpos"						"20"
								"ypos"						"160"
								"command"					"engine ih_crosshair_shape_81"
								"labelText"					"t"
							}
							"CrosshairShape82"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape82"
								"xpos"						"40"
								"ypos"						"160"
								"command"					"engine ih_crosshair_shape_82"
								"labelText"					"u"
							}
							"CrosshairShape83"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape83"
								"xpos"						"60"
								"ypos"						"160"
								"command"					"engine ih_crosshair_shape_83"
								"labelText"					"v"
							}
							"CrosshairShape84"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape84"
								"xpos"						"80"
								"ypos"						"160"
								"command"					"engine ih_crosshair_shape_84"
								"labelText"					"w"
							}
							"CrosshairShape85"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape85"
								"xpos"						"100"
								"ypos"						"160"
								"command"					"engine ih_crosshair_shape_85"
								"labelText"					"x"
							}
							"CrosshairShape86"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape86"
								"xpos"						"120"
								"ypos"						"160"
								"command"					"engine ih_crosshair_shape_86"
								"labelText"					"y"
							}
							"CrosshairShape87"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape87"
								"xpos"						"140"
								"ypos"						"160"
								"command"					"engine ih_crosshair_shape_87"
								"labelText"					"z"
							}
							"CrosshairShape88"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_1"
								"border_armed"				"FLAT_Black_1"
								"defaultFgColor_override"	"TextT4"
								"armedfgcolor_override"		"TextT4"
								"fieldName"					"CrosshairShape88"
								"xpos"						"160"
								"ypos"						"160"
								"command"					"engine clear; showconsole; echo Disabled temporarily due to a bug."
								"labelText"					"{"
							}
							"CrosshairShape89"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape89"
								"xpos"						"180"
								"ypos"						"160"
								"command"					"engine ih_crosshair_shape_89"
								"labelText"					"|"
							}
							"CrosshairShape90"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_1"
								"border_armed"				"FLAT_Black_1"
								"defaultFgColor_override"	"TextT4"
								"armedfgcolor_override"		"TextT4"
								"fieldName"					"CrosshairShape90"
								"xpos"						"0"
								"ypos"						"180"
								"command"					"engine clear; showconsole; echo Disabled temporarily due to a bug."
								"labelText"					"}"
							}
							"CrosshairShape91"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"textalignment"				"center"
								"font"						"Crosshairs15"
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
								"fieldName"					"CrosshairShape91"
								"xpos"						"20"
								"ypos"						"180"
								"command"					"engine ih_crosshair_shape_91"
								"labelText"					"~"
							}
						}
					}
				}
			}
		}
	}
}
