"Resource/UI/MainMenuOverride.res"
{
	"MainMenuOverride"
	{
		"CustomizationMenu"
		{
			"MainPanel"
			{
				"SectionContainer"
				{
					"ScoreboardColorizer"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"ScoreboardColorizer"
						"xpos"						"215"
						"ypos"						"290"
						"wide"						"420"
						"tall"						"155"
						"proportionaltoparent"		"1"
						"border"					"NONE_AccentMain_4"
					}
					"Scoreboard"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"Scoreboard"
						"xpos"						"215"
						"ypos"						"290"
						"wide"						"420"
						"tall"						"155"
						"proportionaltoparent"		"1"
						"border"					"NONE_Black_2"
						"Title"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Title"
							"xpos"						"0"
							"ypos"						"0"
							"wide"						"f0"
							"tall"						"20"
							"proportionaltoparent"		"1"
							"font"						"regular14"
							"labelText"					"Scoreboard"
							"fgcolor"					"TextT4"
							"textAlignment"				"center"
							"border"					"NoBorder"
						}
						"Buttons"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"Buttons"
							"xpos"						"5"
							"ypos"						"20"
							"wide"						"f10"
							"tall"						"f25"
							"proportionaltoparent"		"1"
							"border"					"NONE_Black_4"
							"6v6"
							{
								"ControlName"				"CExButton"
								"fieldName"					"6v6"
								"xpos"						"246"
								"ypos"						"0"
								"wide"						"82"
								"tall"						"65"
								"proportionaltoparent"		"1"
								"labelText"					"6v6"
								"textAlignment"				"center"
								"font"						"regular14"
								"paintbackground"			"0"
								"command"					"engine ih_scoreboard_6v6"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"NONE_Black_3"
								"border_armed"				"NONE_Black_2"
							}
							"9v9"
							{
								"ControlName"				"CExButton"
								"fieldName"					"9v9"
								"xpos"						"328"
								"ypos"						"0"
								"wide"						"82"
								"tall"						"65"
								"proportionaltoparent"		"1"
								"labelText"					"9v9"
								"textAlignment"				"center"
								"font"						"regular14"
								"paintbackground"			"0"
								"command"					"engine ih_scoreboard_9v9"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"NONE_Black_3"
								"border_armed"				"NONE_Black_2"
							}
							"12v12"
							{
								"ControlName"				"CExButton"
								"fieldName"					"12v12"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"246"
								"tall"						"f0"
								"proportionaltoparent"		"1"
								"labelText"					"12v12"
								"textAlignment"				"center"
								"font"						"regular14"
								"paintbackground"			"0"
								"command"					"engine ih_scoreboard_12v12"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"NONE_Black_3"
								"border_armed"				"NONE_Black_2"
							}
							"16v16"
							{
								"ControlName"				"CExButton"
								"fieldName"					"16v16"
								"xpos"						"246"
								"ypos"						"65"
								"wide"						"164"
								"tall"						"65"
								"proportionaltoparent"		"1"
								"labelText"					"16v16"
								"textAlignment"				"center"
								"font"						"regular14"
								"paintbackground"			"0"
								"command"					"engine ih_scoreboard_16v16"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"NONE_Black_3"
								"border_armed"				"NONE_Black_2"
							}
						}
					}
				}
			}
		}
	}
}
