"Resource/UI/MainMenuOverride.res"
{
	"MainMenuOverride"
	{
		"CustomizationMenu"
		{
			"MainPanel"
			{
				"SectionContainer"
				{
					"AccentColor"
					{
						"Buttons"
						{
							"C0"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C0"
								"xpos"						"0"
								"ypos"						"0"
								"command"					"engine ih_accent_0"
								"border_default"			"C0_0"
								"border_armed"				"C0_1"
							}
							"C1"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C1"
								"xpos"						"20"
								"ypos"						"0"
								"command"					"engine ih_accent_1"
								"border_default"			"C1_0"
								"border_armed"				"C1_1"
							}
							"C2"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C2"
								"xpos"						"40"
								"ypos"						"0"
								"command"					"engine ih_accent_2"
								"border_default"			"C2_0"
								"border_armed"				"C2_1"
							}
							"C3"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C3"
								"xpos"						"60"
								"ypos"						"0"
								"command"					"engine ih_accent_3"
								"border_default"			"C3_0"
								"border_armed"				"C3_1"
							}
							"C4"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C4"
								"xpos"						"80"
								"ypos"						"0"
								"command"					"engine ih_accent_4"
								"border_default"			"C4_0"
								"border_armed"				"C4_1"
							}
							"C5"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C5"
								"xpos"						"100"
								"ypos"						"0"
								"command"					"engine ih_accent_5"
								"border_default"			"C5_0"
								"border_armed"				"C5_1"
							}
							"C6"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C6"
								"xpos"						"120"
								"ypos"						"0"
								"command"					"engine ih_accent_6"
								"border_default"			"C6_0"
								"border_armed"				"C6_1"
							}
							"C7"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C7"
								"xpos"						"140"
								"ypos"						"0"
								"command"					"engine ih_accent_7"
								"border_default"			"C7_0"
								"border_armed"				"C7_1"
							}
							"C8"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C8"
								"xpos"						"160"
								"ypos"						"0"
								"command"					"engine ih_accent_8"
								"border_default"			"C8_0"
								"border_armed"				"C8_1"
							}
							"C9"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C9"
								"xpos"						"180"
								"ypos"						"0"
								"command"					"engine ih_accent_9"
								"border_default"			"C9_0"
								"border_armed"				"C9_1"
							}
							"C10"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C10"
								"xpos"						"0"
								"ypos"						"20"
								"command"					"engine ih_accent_10"
								"border_default"			"C10_0"
								"border_armed"				"C10_1"
							}
							"C11"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C11"
								"xpos"						"20"
								"ypos"						"20"
								"command"					"engine ih_accent_11"
								"border_default"			"C11_0"
								"border_armed"				"C11_1"
							}
							"C12"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C12"
								"xpos"						"40"
								"ypos"						"20"
								"command"					"engine ih_accent_12"
								"border_default"			"C12_0"
								"border_armed"				"C12_1"
							}
							"C13"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C13"
								"xpos"						"60"
								"ypos"						"20"
								"command"					"engine ih_accent_13"
								"border_default"			"C13_0"
								"border_armed"				"C13_1"
							}
							"C14"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C14"
								"xpos"						"80"
								"ypos"						"20"
								"command"					"engine ih_accent_14"
								"border_default"			"C14_0"
								"border_armed"				"C14_1"
							}
							"C15"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C15"
								"xpos"						"100"
								"ypos"						"20"
								"command"					"engine ih_accent_15"
								"border_default"			"C15_0"
								"border_armed"				"C15_1"
							}
							"C16"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C16"
								"xpos"						"120"
								"ypos"						"20"
								"command"					"engine ih_accent_16"
								"border_default"			"C16_0"
								"border_armed"				"C16_1"
							}
							"C17"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C17"
								"xpos"						"140"
								"ypos"						"20"
								"command"					"engine ih_accent_17"
								"border_default"			"C17_0"
								"border_armed"				"C17_1"
							}
							"C18"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C18"
								"xpos"						"160"
								"ypos"						"20"
								"command"					"engine ih_accent_18"
								"border_default"			"C18_0"
								"border_armed"				"C18_1"
							}
							"C19"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C19"
								"xpos"						"180"
								"ypos"						"20"
								"command"					"engine ih_accent_19"
								"border_default"			"C19_0"
								"border_armed"				"C19_1"
							}
							"C20"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C20"
								"xpos"						"0"
								"ypos"						"40"
								"command"					"engine ih_accent_20"
								"border_default"			"C20_0"
								"border_armed"				"C20_1"
							}
							"C21"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C21"
								"xpos"						"20"
								"ypos"						"40"
								"command"					"engine ih_accent_21"
								"border_default"			"C21_0"
								"border_armed"				"C21_1"
							}
							"C22"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C22"
								"xpos"						"40"
								"ypos"						"40"
								"command"					"engine ih_accent_22"
								"border_default"			"C22_0"
								"border_armed"				"C22_1"
							}
							"C23"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C23"
								"xpos"						"60"
								"ypos"						"40"
								"command"					"engine ih_accent_23"
								"border_default"			"C23_0"
								"border_armed"				"C23_1"
							}
							"C24"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C24"
								"xpos"						"80"
								"ypos"						"40"
								"command"					"engine ih_accent_24"
								"border_default"			"C24_0"
								"border_armed"				"C24_1"
							}
							"C25"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C25"
								"xpos"						"100"
								"ypos"						"40"
								"command"					"engine ih_accent_25"
								"border_default"			"C25_0"
								"border_armed"				"C25_1"
							}
							"C26"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C26"
								"xpos"						"120"
								"ypos"						"40"
								"command"					"engine ih_accent_26"
								"border_default"			"C26_0"
								"border_armed"				"C26_1"
							}
							"C27"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C27"
								"xpos"						"140"
								"ypos"						"40"
								"command"					"engine ih_accent_27"
								"border_default"			"C27_0"
								"border_armed"				"C27_1"
							}
							"C28"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C28"
								"xpos"						"160"
								"ypos"						"40"
								"command"					"engine ih_accent_28"
								"border_default"			"C28_0"
								"border_armed"				"C28_1"
							}
							"C29"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C29"
								"xpos"						"180"
								"ypos"						"40"
								"command"					"engine ih_accent_29"
								"border_default"			"C29_0"
								"border_armed"				"C29_1"
							}
							"C30"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C30"
								"xpos"						"0"
								"ypos"						"60"
								"command"					"engine ih_accent_30"
								"border_default"			"C30_0"
								"border_armed"				"C30_1"
							}
							"C31"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C31"
								"xpos"						"20"
								"ypos"						"60"
								"command"					"engine ih_accent_31"
								"border_default"			"C31_0"
								"border_armed"				"C31_1"
							}
							"C32"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C32"
								"xpos"						"40"
								"ypos"						"60"
								"command"					"engine ih_accent_32"
								"border_default"			"C32_0"
								"border_armed"				"C32_1"
							}
							"C33"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C33"
								"xpos"						"60"
								"ypos"						"60"
								"command"					"engine ih_accent_33"
								"border_default"			"C33_0"
								"border_armed"				"C33_1"
							}
							"C34"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C34"
								"xpos"						"80"
								"ypos"						"60"
								"command"					"engine ih_accent_34"
								"border_default"			"C34_0"
								"border_armed"				"C34_1"
							}
							"C35"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C35"
								"xpos"						"100"
								"ypos"						"60"
								"command"					"engine ih_accent_35"
								"border_default"			"C35_0"
								"border_armed"				"C35_1"
							}
							"C36"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C36"
								"xpos"						"120"
								"ypos"						"60"
								"command"					"engine ih_accent_36"
								"border_default"			"C36_0"
								"border_armed"				"C36_1"
							}
							"C37"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C37"
								"xpos"						"140"
								"ypos"						"60"
								"command"					"engine ih_accent_37"
								"border_default"			"C37_0"
								"border_armed"				"C37_1"
							}
							"C38"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C38"
								"xpos"						"160"
								"ypos"						"60"
								"command"					"engine ih_accent_38"
								"border_default"			"C38_0"
								"border_armed"				"C38_1"
							}
							"C39"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C39"
								"xpos"						"180"
								"ypos"						"60"
								"command"					"engine ih_accent_39"
								"border_default"			"C39_0"
								"border_armed"				"C39_1"
							}
							"C40"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C40"
								"xpos"						"0"
								"ypos"						"80"
								"command"					"engine ih_accent_40"
								"border_default"			"C40_0"
								"border_armed"				"C40_1"
							}
							"C41"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C41"
								"xpos"						"20"
								"ypos"						"80"
								"command"					"engine ih_accent_41"
								"border_default"			"C41_0"
								"border_armed"				"C41_1"
							}
							"C42"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C42"
								"xpos"						"40"
								"ypos"						"80"
								"command"					"engine ih_accent_42"
								"border_default"			"C42_0"
								"border_armed"				"C42_1"
							}
							"C43"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C43"
								"xpos"						"60"
								"ypos"						"80"
								"command"					"engine ih_accent_43"
								"border_default"			"C43_0"
								"border_armed"				"C43_1"
							}
							"C44"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C44"
								"xpos"						"80"
								"ypos"						"80"
								"command"					"engine ih_accent_44"
								"border_default"			"C44_0"
								"border_armed"				"C44_1"
							}
							"C45"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C45"
								"xpos"						"100"
								"ypos"						"80"
								"command"					"engine ih_accent_45"
								"border_default"			"C45_0"
								"border_armed"				"C45_1"
							}
							"C46"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C46"
								"xpos"						"120"
								"ypos"						"80"
								"command"					"engine ih_accent_46"
								"border_default"			"C46_0"
								"border_armed"				"C46_1"
							}
							"C47"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C47"
								"xpos"						"140"
								"ypos"						"80"
								"command"					"engine ih_accent_47"
								"border_default"			"C47_0"
								"border_armed"				"C47_1"
							}
							"C48"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C48"
								"xpos"						"160"
								"ypos"						"80"
								"command"					"engine ih_accent_48"
								"border_default"			"C48_0"
								"border_armed"				"C48_1"
							}
							"C49"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C49"
								"xpos"						"180"
								"ypos"						"80"
								"command"					"engine ih_accent_49"
								"border_default"			"C49_0"
								"border_armed"				"C49_1"
							}
							"C50"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C50"
								"xpos"						"0"
								"ypos"						"100"
								"command"					"engine ih_accent_50"
								"border_default"			"C50_0"
								"border_armed"				"C50_1"
							}
							"C51"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C51"
								"xpos"						"20"
								"ypos"						"100"
								"command"					"engine ih_accent_51"
								"border_default"			"C51_0"
								"border_armed"				"C51_1"
							}
							"C52"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C52"
								"xpos"						"40"
								"ypos"						"100"
								"command"					"engine ih_accent_52"
								"border_default"			"C52_0"
								"border_armed"				"C52_1"
							}
							"C53"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C53"
								"xpos"						"60"
								"ypos"						"100"
								"command"					"engine ih_accent_53"
								"border_default"			"C53_0"
								"border_armed"				"C53_1"
							}
							"C54"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C54"
								"xpos"						"80"
								"ypos"						"100"
								"command"					"engine ih_accent_54"
								"border_default"			"C54_0"
								"border_armed"				"C54_1"
							}
							"C55"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C55"
								"xpos"						"100"
								"ypos"						"100"
								"command"					"engine ih_accent_55"
								"border_default"			"C55_0"
								"border_armed"				"C55_1"
							}
							"C56"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C56"
								"xpos"						"120"
								"ypos"						"100"
								"command"					"engine ih_accent_56"
								"border_default"			"C56_0"
								"border_armed"				"C56_1"
							}
							"C57"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C57"
								"xpos"						"140"
								"ypos"						"100"
								"command"					"engine ih_accent_57"
								"border_default"			"C57_0"
								"border_armed"				"C57_1"
							}
							"C58"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C58"
								"xpos"						"160"
								"ypos"						"100"
								"command"					"engine ih_accent_58"
								"border_default"			"C58_0"
								"border_armed"				"C58_1"
							}
							"C59"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C59"
								"xpos"						"180"
								"ypos"						"100"
								"command"					"engine ih_accent_59"
								"border_default"			"C59_0"
								"border_armed"				"C59_1"
							}
							"C60"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C60"
								"xpos"						"0"
								"ypos"						"120"
								"command"					"engine ih_accent_60"
								"border_default"			"C60_0"
								"border_armed"				"C60_1"
							}
							"C61"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C61"
								"xpos"						"20"
								"ypos"						"120"
								"command"					"engine ih_accent_61"
								"border_default"			"C61_0"
								"border_armed"				"C61_1"
							}
							"C62"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C62"
								"xpos"						"40"
								"ypos"						"120"
								"command"					"engine ih_accent_62"
								"border_default"			"C62_0"
								"border_armed"				"C62_1"
							}
							"C63"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C63"
								"xpos"						"60"
								"ypos"						"120"
								"command"					"engine ih_accent_63"
								"border_default"			"C63_0"
								"border_armed"				"C63_1"
							}
							"C64"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C64"
								"xpos"						"80"
								"ypos"						"120"
								"command"					"engine ih_accent_64"
								"border_default"			"C64_0"
								"border_armed"				"C64_1"
							}
							"C65"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C65"
								"xpos"						"100"
								"ypos"						"120"
								"command"					"engine ih_accent_65"
								"border_default"			"C65_0"
								"border_armed"				"C65_1"
							}
							"C66"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C66"
								"xpos"						"120"
								"ypos"						"120"
								"command"					"engine ih_accent_66"
								"border_default"			"C66_0"
								"border_armed"				"C66_1"
							}
							"C67"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C67"
								"xpos"						"140"
								"ypos"						"120"
								"command"					"engine ih_accent_67"
								"border_default"			"C67_0"
								"border_armed"				"C67_1"
							}
							"C68"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C68"
								"xpos"						"160"
								"ypos"						"120"
								"command"					"engine ih_accent_68"
								"border_default"			"C68_0"
								"border_armed"				"C68_1"
							}
							"C69"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C69"
								"xpos"						"180"
								"ypos"						"120"
								"command"					"engine ih_accent_69"
								"border_default"			"C69_0"
								"border_armed"				"C69_1"
							}
							"C70"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C70"
								"xpos"						"0"
								"ypos"						"140"
								"command"					"engine ih_accent_70"
								"border_default"			"C70_0"
								"border_armed"				"C70_1"
							}
							"C71"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C71"
								"xpos"						"20"
								"ypos"						"140"
								"command"					"engine ih_accent_71"
								"border_default"			"C71_0"
								"border_armed"				"C71_1"
							}
							"C72"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C72"
								"xpos"						"40"
								"ypos"						"140"
								"command"					"engine ih_accent_72"
								"border_default"			"C72_0"
								"border_armed"				"C72_1"
							}
							"C73"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C73"
								"xpos"						"60"
								"ypos"						"140"
								"command"					"engine ih_accent_73"
								"border_default"			"C73_0"
								"border_armed"				"C73_1"
							}
							"C74"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C74"
								"xpos"						"80"
								"ypos"						"140"
								"command"					"engine ih_accent_74"
								"border_default"			"C74_0"
								"border_armed"				"C74_1"
							}
							"C75"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C75"
								"xpos"						"100"
								"ypos"						"140"
								"command"					"engine ih_accent_75"
								"border_default"			"C75_0"
								"border_armed"				"C75_1"
							}
							"C76"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C76"
								"xpos"						"120"
								"ypos"						"140"
								"command"					"engine ih_accent_76"
								"border_default"			"C76_0"
								"border_armed"				"C76_1"
							}
							"C77"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C77"
								"xpos"						"140"
								"ypos"						"140"
								"command"					"engine ih_accent_77"
								"border_default"			"C77_0"
								"border_armed"				"C77_1"
							}
							"C78"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C78"
								"xpos"						"160"
								"ypos"						"140"
								"command"					"engine ih_accent_78"
								"border_default"			"C78_0"
								"border_armed"				"C78_1"
							}
							"C79"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C79"
								"xpos"						"180"
								"ypos"						"140"
								"command"					"engine ih_accent_79"
								"border_default"			"C79_0"
								"border_armed"				"C79_1"
							}
							"C80"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C80"
								"xpos"						"0"
								"ypos"						"160"
								"command"					"engine ih_accent_80"
								"border_default"			"C80_0"
								"border_armed"				"C80_1"
							}
							"C81"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C81"
								"xpos"						"20"
								"ypos"						"160"
								"command"					"engine ih_accent_81"
								"border_default"			"C81_0"
								"border_armed"				"C81_1"
							}
							"C82"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C82"
								"xpos"						"40"
								"ypos"						"160"
								"command"					"engine ih_accent_82"
								"border_default"			"C82_0"
								"border_armed"				"C82_1"
							}
							"C83"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C83"
								"xpos"						"60"
								"ypos"						"160"
								"command"					"engine ih_accent_83"
								"border_default"			"C83_0"
								"border_armed"				"C83_1"
							}
							"C84"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C84"
								"xpos"						"80"
								"ypos"						"160"
								"command"					"engine ih_accent_84"
								"border_default"			"C84_0"
								"border_armed"				"C84_1"
							}
							"C85"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C85"
								"xpos"						"100"
								"ypos"						"160"
								"command"					"engine ih_accent_85"
								"border_default"			"C85_0"
								"border_armed"				"C85_1"
							}
							"C86"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C86"
								"xpos"						"120"
								"ypos"						"160"
								"command"					"engine ih_accent_86"
								"border_default"			"C86_0"
								"border_armed"				"C86_1"
							}
							"C87"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C87"
								"xpos"						"140"
								"ypos"						"160"
								"command"					"engine ih_accent_87"
								"border_default"			"C87_0"
								"border_armed"				"C87_1"
							}
							"C88"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C88"
								"xpos"						"160"
								"ypos"						"160"
								"command"					"engine ih_accent_88"
								"border_default"			"C88_0"
								"border_armed"				"C88_1"
							}
							"C89"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C89"
								"xpos"						"180"
								"ypos"						"160"
								"command"					"engine ih_accent_89"
								"border_default"			"C89_0"
								"border_armed"				"C89_1"
							}
							"C90"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C90"
								"xpos"						"0"
								"ypos"						"180"
								"command"					"engine ih_accent_90"
								"border_default"			"C90_0"
								"border_armed"				"C90_1"
							}
							"C91"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C91"
								"xpos"						"20"
								"ypos"						"180"
								"command"					"engine ih_accent_91"
								"border_default"			"C91_0"
								"border_armed"				"C91_1"
							}
							"C92"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C92"
								"xpos"						"40"
								"ypos"						"180"
								"command"					"engine ih_accent_92"
								"border_default"			"C92_0"
								"border_armed"				"C92_1"
							}
							"C93"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C93"
								"xpos"						"60"
								"ypos"						"180"
								"command"					"engine ih_accent_93"
								"border_default"			"C93_0"
								"border_armed"				"C93_1"
							}
							"C94"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C94"
								"xpos"						"80"
								"ypos"						"180"
								"command"					"engine ih_accent_94"
								"border_default"			"C94_0"
								"border_armed"				"C94_1"
							}
							"C95"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C95"
								"xpos"						"100"
								"ypos"						"180"
								"command"					"engine ih_accent_95"
								"border_default"			"C95_0"
								"border_armed"				"C95_1"
							}
							"C96"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C96"
								"xpos"						"120"
								"ypos"						"180"
								"command"					"engine ih_accent_96"
								"border_default"			"C96_0"
								"border_armed"				"C96_1"
							}
							"C97"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C97"
								"xpos"						"140"
								"ypos"						"180"
								"command"					"engine ih_accent_97"
								"border_default"			"C97_0"
								"border_armed"				"C97_1"
							}
							"C98"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C98"
								"xpos"						"160"
								"ypos"						"180"
								"command"					"engine ih_accent_98"
								"border_default"			"C98_0"
								"border_armed"				"C98_1"
							}
							"C99"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C99"
								"xpos"						"180"
								"ypos"						"180"
								"command"					"engine ih_accent_99"
								"border_default"			"C99_0"
								"border_armed"				"C99_1"
							}
							"C100"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C100"
								"xpos"						"0"
								"ypos"						"200"
								"command"					"engine ih_accent_100"
								"border_default"			"C100_0"
								"border_armed"				"C100_1"
							}
							"C101"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C101"
								"xpos"						"20"
								"ypos"						"200"
								"command"					"engine ih_accent_101"
								"border_default"			"C101_0"
								"border_armed"				"C101_1"
							}
							"C102"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C102"
								"xpos"						"40"
								"ypos"						"200"
								"command"					"engine ih_accent_102"
								"border_default"			"C102_0"
								"border_armed"				"C102_1"
							}
							"C103"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C103"
								"xpos"						"60"
								"ypos"						"200"
								"command"					"engine ih_accent_103"
								"border_default"			"C103_0"
								"border_armed"				"C103_1"
							}
							"C104"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C104"
								"xpos"						"80"
								"ypos"						"200"
								"command"					"engine ih_accent_104"
								"border_default"			"C104_0"
								"border_armed"				"C104_1"
							}
							"C105"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C105"
								"xpos"						"100"
								"ypos"						"200"
								"command"					"engine ih_accent_105"
								"border_default"			"C105_0"
								"border_armed"				"C105_1"
							}
							"C106"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C106"
								"xpos"						"120"
								"ypos"						"200"
								"command"					"engine ih_accent_106"
								"border_default"			"C106_0"
								"border_armed"				"C106_1"
							}
							"C107"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C107"
								"xpos"						"140"
								"ypos"						"200"
								"command"					"engine ih_accent_107"
								"border_default"			"C107_0"
								"border_armed"				"C107_1"
							}
							"C108"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C108"
								"xpos"						"160"
								"ypos"						"200"
								"command"					"engine ih_accent_108"
								"border_default"			"C108_0"
								"border_armed"				"C108_1"
							}
							"C109"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C109"
								"xpos"						"180"
								"ypos"						"200"
								"command"					"engine ih_accent_109"
								"border_default"			"C109_0"
								"border_armed"				"C109_1"
							}
							"C110"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C110"
								"xpos"						"0"
								"ypos"						"220"
								"command"					"engine ih_accent_110"
								"border_default"			"C110_0"
								"border_armed"				"C110_1"
							}
							"C111"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C111"
								"xpos"						"20"
								"ypos"						"220"
								"command"					"engine ih_accent_111"
								"border_default"			"C111_0"
								"border_armed"				"C111_1"
							}
							"C112"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C112"
								"xpos"						"40"
								"ypos"						"220"
								"command"					"engine ih_accent_112"
								"border_default"			"C112_0"
								"border_armed"				"C112_1"
							}
							"C113"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C113"
								"xpos"						"60"
								"ypos"						"220"
								"command"					"engine ih_accent_113"
								"border_default"			"C113_0"
								"border_armed"				"C113_1"
							}
							"C114"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C114"
								"xpos"						"80"
								"ypos"						"220"
								"command"					"engine ih_accent_114"
								"border_default"			"C114_0"
								"border_armed"				"C114_1"
							}
							"C115"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C115"
								"xpos"						"100"
								"ypos"						"220"
								"command"					"engine ih_accent_115"
								"border_default"			"C115_0"
								"border_armed"				"C115_1"
							}
							"C116"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C116"
								"xpos"						"120"
								"ypos"						"220"
								"command"					"engine ih_accent_116"
								"border_default"			"C116_0"
								"border_armed"				"C116_1"
							}
							"C117"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C117"
								"xpos"						"140"
								"ypos"						"220"
								"command"					"engine ih_accent_117"
								"border_default"			"C117_0"
								"border_armed"				"C117_1"
							}
							"C118"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C118"
								"xpos"						"160"
								"ypos"						"220"
								"command"					"engine ih_accent_118"
								"border_default"			"C118_0"
								"border_armed"				"C118_1"
							}
							"C119"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C119"
								"xpos"						"180"
								"ypos"						"220"
								"command"					"engine ih_accent_119"
								"border_default"			"C119_0"
								"border_armed"				"C119_1"
							}
							"C120"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C120"
								"xpos"						"0"
								"ypos"						"240"
								"command"					"engine ih_accent_120"
								"border_default"			"C120_0"
								"border_armed"				"C120_1"
							}
							"C121"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C121"
								"xpos"						"20"
								"ypos"						"240"
								"command"					"engine ih_accent_121"
								"border_default"			"C121_0"
								"border_armed"				"C121_1"
							}
							"C122"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C122"
								"xpos"						"40"
								"ypos"						"240"
								"command"					"engine ih_accent_122"
								"border_default"			"C122_0"
								"border_armed"				"C122_1"
							}
							"C123"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C123"
								"xpos"						"60"
								"ypos"						"240"
								"command"					"engine ih_accent_123"
								"border_default"			"C123_0"
								"border_armed"				"C123_1"
							}
							"C124"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C124"
								"xpos"						"80"
								"ypos"						"240"
								"command"					"engine ih_accent_124"
								"border_default"			"C124_0"
								"border_armed"				"C124_1"
							}
							"C125"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C125"
								"xpos"						"100"
								"ypos"						"240"
								"command"					"engine ih_accent_125"
								"border_default"			"C125_0"
								"border_armed"				"C125_1"
							}
							"C126"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C126"
								"xpos"						"120"
								"ypos"						"240"
								"command"					"engine ih_accent_126"
								"border_default"			"C126_0"
								"border_armed"				"C126_1"
							}
							"C127"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C127"
								"xpos"						"140"
								"ypos"						"240"
								"command"					"engine ih_accent_127"
								"border_default"			"C127_0"
								"border_armed"				"C127_1"
							}
							"C128"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C128"
								"xpos"						"160"
								"ypos"						"240"
								"command"					"engine ih_accent_128"
								"border_default"			"C128_0"
								"border_armed"				"C128_1"
							}
							"C129"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C129"
								"xpos"						"180"
								"ypos"						"240"
								"command"					"engine ih_accent_129"
								"border_default"			"C129_0"
								"border_armed"				"C129_1"
							}
							"C130"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C130"
								"xpos"						"0"
								"ypos"						"260"
								"command"					"engine ih_accent_130"
								"border_default"			"C130_0"
								"border_armed"				"C130_1"
							}
							"C131"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C131"
								"xpos"						"20"
								"ypos"						"260"
								"command"					"engine ih_accent_131"
								"border_default"			"C131_0"
								"border_armed"				"C131_1"
							}
							"C132"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C132"
								"xpos"						"40"
								"ypos"						"260"
								"command"					"engine ih_accent_132"
								"border_default"			"C132_0"
								"border_armed"				"C132_1"
							}
							"C133"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C133"
								"xpos"						"60"
								"ypos"						"260"
								"command"					"engine ih_accent_133"
								"border_default"			"C133_0"
								"border_armed"				"C133_1"
							}
							"C134"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C134"
								"xpos"						"80"
								"ypos"						"260"
								"command"					"engine ih_accent_134"
								"border_default"			"C134_0"
								"border_armed"				"C134_1"
							}
							"C135"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C135"
								"xpos"						"100"
								"ypos"						"260"
								"command"					"engine ih_accent_135"
								"border_default"			"C135_0"
								"border_armed"				"C135_1"
							}
							"C136"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C136"
								"xpos"						"120"
								"ypos"						"260"
								"command"					"engine ih_accent_136"
								"border_default"			"C136_0"
								"border_armed"				"C136_1"
							}
							"C137"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C137"
								"xpos"						"140"
								"ypos"						"260"
								"command"					"engine ih_accent_137"
								"border_default"			"C137_0"
								"border_armed"				"C137_1"
							}
							"C138"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C138"
								"xpos"						"160"
								"ypos"						"260"
								"command"					"engine ih_accent_138"
								"border_default"			"C138_0"
								"border_armed"				"C138_1"
							}
							"C139"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C139"
								"xpos"						"180"
								"ypos"						"260"
								"command"					"engine ih_accent_139"
								"border_default"			"C139_0"
								"border_armed"				"C139_1"
							}
							"C140"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C140"
								"xpos"						"0"
								"ypos"						"280"
								"command"					"engine ih_accent_140"
								"border_default"			"C140_0"
								"border_armed"				"C140_1"
							}
							"C141"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C141"
								"xpos"						"20"
								"ypos"						"280"
								"command"					"engine ih_accent_141"
								"border_default"			"C141_0"
								"border_armed"				"C141_1"
							}
							"C142"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C142"
								"xpos"						"40"
								"ypos"						"280"
								"command"					"engine ih_accent_142"
								"border_default"			"C142_0"
								"border_armed"				"C142_1"
							}
							"C143"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C143"
								"xpos"						"60"
								"ypos"						"280"
								"command"					"engine ih_accent_143"
								"border_default"			"C143_0"
								"border_armed"				"C143_1"
							}
							"C144"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C144"
								"xpos"						"80"
								"ypos"						"280"
								"command"					"engine ih_accent_144"
								"border_default"			"C144_0"
								"border_armed"				"C144_1"
							}
							"C145"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C145"
								"xpos"						"100"
								"ypos"						"280"
								"command"					"engine ih_accent_145"
								"border_default"			"C145_0"
								"border_armed"				"C145_1"
							}
							"C146"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C146"
								"xpos"						"120"
								"ypos"						"280"
								"command"					"engine ih_accent_146"
								"border_default"			"C146_0"
								"border_armed"				"C146_1"
							}
							"C147"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C147"
								"xpos"						"140"
								"ypos"						"280"
								"command"					"engine ih_accent_147"
								"border_default"			"C147_0"
								"border_armed"				"C147_1"
							}
							"C148"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C148"
								"xpos"						"160"
								"ypos"						"280"
								"command"					"engine ih_accent_148"
								"border_default"			"C148_0"
								"border_armed"				"C148_1"
							}
							"C149"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C149"
								"xpos"						"180"
								"ypos"						"280"
								"command"					"engine ih_accent_149"
								"border_default"			"C149_0"
								"border_armed"				"C149_1"
							}
							"C150"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C150"
								"xpos"						"0"
								"ypos"						"300"
								"command"					"engine ih_accent_150"
								"border_default"			"C150_0"
								"border_armed"				"C150_1"
							}
							"C151"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C151"
								"xpos"						"20"
								"ypos"						"300"
								"command"					"engine ih_accent_151"
								"border_default"			"C151_0"
								"border_armed"				"C151_1"
							}
							"C152"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C152"
								"xpos"						"40"
								"ypos"						"300"
								"command"					"engine ih_accent_152"
								"border_default"			"C152_0"
								"border_armed"				"C152_1"
							}
							"C153"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C153"
								"xpos"						"60"
								"ypos"						"300"
								"command"					"engine ih_accent_153"
								"border_default"			"C153_0"
								"border_armed"				"C153_1"
							}
							"C154"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C154"
								"xpos"						"80"
								"ypos"						"300"
								"command"					"engine ih_accent_154"
								"border_default"			"C154_0"
								"border_armed"				"C154_1"
							}
							"C155"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C155"
								"xpos"						"100"
								"ypos"						"300"
								"command"					"engine ih_accent_155"
								"border_default"			"C155_0"
								"border_armed"				"C155_1"
							}
							"C156"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C156"
								"xpos"						"120"
								"ypos"						"300"
								"command"					"engine ih_accent_156"
								"border_default"			"C156_0"
								"border_armed"				"C156_1"
							}
							"C157"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C157"
								"xpos"						"140"
								"ypos"						"300"
								"command"					"engine ih_accent_157"
								"border_default"			"C157_0"
								"border_armed"				"C157_1"
							}
							"C158"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C158"
								"xpos"						"160"
								"ypos"						"300"
								"command"					"engine ih_accent_158"
								"border_default"			"C158_0"
								"border_armed"				"C158_1"
							}
							"C159"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C159"
								"xpos"						"180"
								"ypos"						"300"
								"command"					"engine ih_accent_159"
								"border_default"			"C159_0"
								"border_armed"				"C159_1"
							}
							"C160"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C160"
								"xpos"						"0"
								"ypos"						"320"
								"command"					"engine ih_accent_160"
								"border_default"			"C160_0"
								"border_armed"				"C160_1"
							}
							"C161"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C161"
								"xpos"						"20"
								"ypos"						"320"
								"command"					"engine ih_accent_161"
								"border_default"			"C161_0"
								"border_armed"				"C161_1"
							}
							"C162"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C162"
								"xpos"						"40"
								"ypos"						"320"
								"command"					"engine ih_accent_162"
								"border_default"			"C162_0"
								"border_armed"				"C162_1"
							}
							"C163"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C163"
								"xpos"						"60"
								"ypos"						"320"
								"command"					"engine ih_accent_163"
								"border_default"			"C163_0"
								"border_armed"				"C163_1"
							}
							"C164"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C164"
								"xpos"						"80"
								"ypos"						"320"
								"command"					"engine ih_accent_164"
								"border_default"			"C164_0"
								"border_armed"				"C164_1"
							}
							"C165"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C165"
								"xpos"						"100"
								"ypos"						"320"
								"command"					"engine ih_accent_165"
								"border_default"			"C165_0"
								"border_armed"				"C165_1"
							}
							"C166"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C166"
								"xpos"						"120"
								"ypos"						"320"
								"command"					"engine ih_accent_166"
								"border_default"			"C166_0"
								"border_armed"				"C166_1"
							}
							"C167"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C167"
								"xpos"						"140"
								"ypos"						"320"
								"command"					"engine ih_accent_167"
								"border_default"			"C167_0"
								"border_armed"				"C167_1"
							}
							"C168"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C168"
								"xpos"						"160"
								"ypos"						"320"
								"command"					"engine ih_accent_168"
								"border_default"			"C168_0"
								"border_armed"				"C168_1"
							}
							"C169"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C169"
								"xpos"						"180"
								"ypos"						"320"
								"command"					"engine ih_accent_169"
								"border_default"			"C169_0"
								"border_armed"				"C169_1"
							}
							"C170"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C170"
								"xpos"						"0"
								"ypos"						"340"
								"command"					"engine ih_accent_170"
								"border_default"			"C170_0"
								"border_armed"				"C170_1"
							}
							"C171"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C171"
								"xpos"						"20"
								"ypos"						"340"
								"command"					"engine ih_accent_171"
								"border_default"			"C171_0"
								"border_armed"				"C171_1"
							}
							"C172"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C172"
								"xpos"						"40"
								"ypos"						"340"
								"command"					"engine ih_accent_172"
								"border_default"			"C172_0"
								"border_armed"				"C172_1"
							}
							"C173"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C173"
								"xpos"						"60"
								"ypos"						"340"
								"command"					"engine ih_accent_173"
								"border_default"			"C173_0"
								"border_armed"				"C173_1"
							}
							"C174"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C174"
								"xpos"						"80"
								"ypos"						"340"
								"command"					"engine ih_accent_174"
								"border_default"			"C174_0"
								"border_armed"				"C174_1"
							}
							"C175"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C175"
								"xpos"						"100"
								"ypos"						"340"
								"command"					"engine ih_accent_175"
								"border_default"			"C175_0"
								"border_armed"				"C175_1"
							}
							"C176"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C176"
								"xpos"						"120"
								"ypos"						"340"
								"command"					"engine ih_accent_176"
								"border_default"			"C176_0"
								"border_armed"				"C176_1"
							}
							"C177"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C177"
								"xpos"						"140"
								"ypos"						"340"
								"command"					"engine ih_accent_177"
								"border_default"			"C177_0"
								"border_armed"				"C177_1"
							}
							"C178"
							{
								"ControlName"				"CExButton"
								"wide"						"20"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"fieldName"					"C178"
								"xpos"						"160"
								"ypos"						"340"
								"command"					"engine ih_accent_178"
								"border_default"			"C178_0"
								"border_armed"				"C178_1"
							}
						}
					}
				}
			}
		}
	}
}
