"Resource/UI/MainMenuOverride.res"
{
	"MainMenuOverride"
	{
		"CustomizationMenu"
		{
			"MainPanel"
			{
				"SectionContainer"
				{
					"AccentColor"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"AccentColor"
						"xpos"						"5"
						"ypos"						"5"
						"wide"						"190"
						"tall"						"90"
						"proportionaltoparent"		"1"
						"border"					"TLTRBLBR_PanelO1_0"
						"Title"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Title"
							"xpos"						"0"
							"ypos"						"0"
							"wide"						"f0"
							"tall"						"20"
							"proportionaltoparent"		"1"
							"font"						"regular14"
							"labelText"					"Accent Color"
							"fgcolor"					"Text4"
							"textAlignment"				"center"
							"border"					"NoBorder"
						}
						"Buttons"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"Buttons"
							"xpos"						"5"
							"ypos"						"25"
							"wide"						"180"
							"tall"						"60"
							"proportionaltoparent"		"1"
							"border"					"TLTRBLBR_PanelO0_0"
							"C0"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C0"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_0"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C0_0"
								"border_armed"				"C0_1"
							}
							"C30"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C30"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_30"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C30_0"
								"border_armed"				"C30_1"
								"pin_to_sibling"			"C0"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_TOPRIGHT"
							}
							"C60"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C60"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_60"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C60_0"
								"border_armed"				"C60_1"
								"pin_to_sibling"			"C30"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_TOPRIGHT"
							}
							"C90"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C90"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_90"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C90_0"
								"border_armed"				"C90_1"
								"pin_to_sibling"			"C0"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
							}
							"C120"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C120"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_120"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C120_0"
								"border_armed"				"C120_1"
								"pin_to_sibling"			"C90"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_TOPRIGHT"
							}
							"C150"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C150"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_150"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C150_0"
								"border_armed"				"C150_1"
								"pin_to_sibling"			"C120"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_TOPRIGHT"
							}
							"C180"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C180"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_180"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C180_0"
								"border_armed"				"C180_1"
								"pin_to_sibling"			"C90"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
							}
							"C210"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C210"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_210"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C210_0"
								"border_armed"				"C210_1"
								"pin_to_sibling"			"C180"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_TOPRIGHT"
							}
							"C240"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C240"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_240"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C240_0"
								"border_armed"				"C240_1"
								"pin_to_sibling"			"C210"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_TOPRIGHT"
							}
							"C270"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C270"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_270"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C270_0"
								"border_armed"				"C270_1"
								"pin_to_sibling"			"C180"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
							}
							"C300"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C300"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_300"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C300_0"
								"border_armed"				"C300_1"
								"pin_to_sibling"			"C270"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_TOPRIGHT"
							}
							"C330"
							{
								"ControlName"				"CExButton"
								"fieldName"					"C330"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"15"
								"proportionaltoparent"		"1"
								"labelText"					""
								"paintbackground"			"0"
								"command"					"engine ih_accent_330"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"C330_0"
								"border_armed"				"C330_1"
								"pin_to_sibling"			"C300"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_TOPRIGHT"
							}
						}
					}
				}
			}
		}
	}
}
