"Resource/UI/MainMenuOverride.res"
{
	"MainMenuOverride"
	{
		"CustomizationMenu"
		{
			"MainPanel"
			{
				"SectionContainer"
				{
					"ColorsSection"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"ColorsSection"
						"xpos"						"0"
						"ypos"						"0"
						"wide"						"200"
						"tall"						"f0"
						"proportionaltoparent"		"1"
						"border"					"NoBorder"
						"Title"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Title"
							"xpos"						"0"
							"ypos"						"0"
							"wide"						"f0"
							"tall"						"20"
							"proportionaltoparent"		"1"
							"font"						"bold18"
							"labelText"					"COLORS"
							"textAlignment"				"center"
							"border"					"NoBorder"
						}
						"ColorSelection"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"ColorSelection"
							"xpos"						"5"
							"ypos"						"20"
							"wide"						"f10"
							"tall"						"60"
							"proportionaltoparent"		"1"
							"border"					"TLTRBLBR_PanelO2_0"
							"Title"
							{
								"ControlName"					"CExLabel"
								"fieldName"						"Title"
								"xpos"							"0"
								"ypos"							"0"
								"wide"							"f0"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"font"							"regular14"
								"labelText"						"CHOOSE A COLOR"
								"textAlignment"					"west"
								"textinsetx"					"5"
								"use_proportional_insets"		"1"
								"border"						"TLTR_PanelO1_0"
							}
							"ControlButtons"
							{
								"ControlName"				"EditablePanel"
								"fieldName"					"ControlButtons"
								"xpos"						"rs1-2"
								"ypos"						"2"
								"wide"						"48"
								"tall"						"16"
								"proportionaltoparent"		"1"
								"border"					"TLTRBLBR_PanelO2_0"
								"Reset"
								{
									"ControlName"				"CExButton"
									"fieldName"					"Reset"
									"xpos"						"0"
									"ypos"						"0"
									"wide"						"16"
									"tall"						"16"
									"proportionaltoparent"		"1"
									"labelText"					"r"
									"font"						"iconsSmall"
									"command"					"engine sixense_weapon_select_sensitivity 210"
									"actionsignallevel"			"7"
									"sound_depressed"			"UI/buttonclick.wav"
									"sound_released"			"UI/buttonclickrelease.wav"
									"paintbackground"			"0"
									"border_default"			"NoBorder"
									"border_armed"				"TLBL_PanelO4_0"
								}
								"Decrement"
								{
									"ControlName"				"CExButton"
									"fieldName"					"Decrement"
									"xpos"						"16"
									"ypos"						"0"
									"wide"						"16"
									"tall"						"16"
									"proportionaltoparent"		"1"
									"labelText"					"<"
									"font"						"iconsSmall"
									"command"					"engine incrementvar sixense_weapon_select_sensitivity 0 360 -10"
									"actionsignallevel"			"7"
									"sound_depressed"			"UI/buttonclick.wav"
									"sound_released"			"UI/buttonclickrelease.wav"
									"paintbackground"			"0"
									"border_default"			"NoBorder"
									"border_armed"				"NONE_PanelO4_0"
								}
								"Increment"
								{
									"ControlName"				"CExButton"
									"fieldName"					"Increment"
									"xpos"						"32"
									"ypos"						"0"
									"wide"						"16"
									"tall"						"16"
									"proportionaltoparent"		"1"
									"labelText"					">"
									"font"						"iconsSmall"
									"command"					"engine incrementvar sixense_weapon_select_sensitivity 0 360 10"
									"actionsignallevel"			"7"
									"sound_depressed"			"UI/buttonclick.wav"
									"sound_released"			"UI/buttonclickrelease.wav"
									"paintbackground"			"0"
									"border_default"			"NoBorder"
									"border_armed"				"TRBR_PanelO4_0"
								}
							}
							"HueSlider"
							{
								"ControlName"				"CCvarSlider"
								"fieldName"					"HueSlider"
								"xpos"						"-5"
								"ypos"						"0"
								"wide"						"f10"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"cvar_name"					"sixense_weapon_select_sensitivity"
								"minvalue"					"0"
								"maxvalue"					"360"
								"pin_to_sibling"			"Title"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
							}
							"HueSliderImage"
							{
								"ControlName"				"CTFImagePanel"
								"fieldName"					"HueSliderImage"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"f10"
								"tall"						"5"
								"visible"					"1"
								"enabled"					"1"
								"proportionaltoparent"		"1"
								"image"						"replay/thumbnails/misc/hue_slider"
								"scaleImage"				"1"
								"pin_to_sibling"			"HueSlider"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
							}
						}
						"ApplySelection"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"ApplySelection"
							"xpos"						"0"
							"ypos"						"5"
							"wide"						"f10"
							"tall"						"270"
							"proportionaltoparent"		"1"
							"border"					"TLTRBLBR_PanelO2_0"
							"pin_to_sibling"			"ColorSelection"
							"pin_corner_to_sibling"		"PIN_TOPLEFT"
							"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
							"Title"
							{
								"ControlName"					"CExLabel"
								"fieldName"						"Title"
								"xpos"							"0"
								"ypos"							"0"
								"wide"							"f0"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"font"							"regular14"
								"labelText"						"WHAT TO APPLY TO?"
								"textAlignment"					"west"
								"textinsetx"					"5"
								"use_proportional_insets"		"1"
								"border"						"TLTR_PanelO1_0"
							}
							"Buttons"
							{
								"ControlName"				"EditablePanel"
								"fieldName"					"Buttons"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"f0"
								"tall"						"260"
								"proportionaltoparent"		"1"
								"pin_to_sibling"			"Title"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
								"AccentMain"
								{
									"ControlName"					"CExButton"
									"fieldName"						"AccentMain"
									"xpos"							"0"
									"ypos"							"0"
									"wide"							"f0"
									"tall"							"20"
									"proportionaltoparent"			"1"
									"labelText"						"MAIN MENU, ETC..."
									"font"							"regular14"
									"textAlignment"					"west"
									"textinsetx"					"5"
									"use_proportional_insets"		"1"
									"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_AccentMain; ih_printcolor; ih_incolor"
									"actionsignallevel"				"7"
									"sound_depressed"				"UI/buttonclick.wav"
									"sound_released"				"UI/buttonclickrelease.wav"
									"paintbackground"				"0"
									"border_default"				"NoBorder"
									"border_armed"					"NONE_PanelO4_0"
								}
							}
						}
					}
				}
			}
		}
	}
}
