"Resource/UI/MainMenuOverride.res"
{
	"MainMenuOverride"
	{
		"CustomizationMenu"
		{
			"MainPanel"
			{
				"SectionContainer"
				{
					"ColorsSection"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"ColorsSection"
						"xpos"						"0"
						"ypos"						"0"
						"wide"						"200"
						"tall"						"f0"
						"proportionaltoparent"		"1"
						"border"					"NoBorder"
						"Title"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Title"
							"xpos"						"0"
							"ypos"						"0"
							"wide"						"f0"
							"tall"						"20"
							"proportionaltoparent"		"1"
							"font"						"bold18"
							"labelText"					"COLORS"
							"textAlignment"				"center"
							"border"					"NoBorder"
						}
						"ColorSelection"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"ColorSelection"
							"xpos"						"5"
							"ypos"						"20"
							"wide"						"f10"
							"tall"						"50"
							"proportionaltoparent"		"1"
							"border"					"TLTRBLBR_PanelO2_0"
							"Title"
							{
								"ControlName"					"CExLabel"
								"fieldName"						"Title"
								"xpos"							"0"
								"ypos"							"0"
								"wide"							"f0"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"font"							"regular14"
								"labelText"						"CHOOSE A COLOR"
								"textAlignment"					"west"
								"textinsetx"					"5"
								"use_proportional_insets"		"1"
								"border"						"TLTR_PanelO1_0"
							}
							"ControlButtons"
							{
								"ControlName"				"EditablePanel"
								"fieldName"					"ControlButtons"
								"xpos"						"rs1-2"
								"ypos"						"2"
								"wide"						"32"
								"tall"						"16"
								"proportionaltoparent"		"1"
								"border"					"TLTRBLBR_PanelO2_0"
								"Decrement"
								{
									"ControlName"				"CExButton"
									"fieldName"					"Decrement"
									"xpos"						"0"
									"ypos"						"0"
									"wide"						"16"
									"tall"						"16"
									"proportionaltoparent"		"1"
									"labelText"					"<"
									"font"						"iconsSmall"
									"textalignment"				"center"
									"command"					"engine incrementvar sixense_weapon_select_sensitivity 0 360 -10"
									"actionsignallevel"			"7"
									"sound_depressed"			"UI/buttonclick.wav"
									"sound_released"			"UI/buttonclickrelease.wav"
									"paintbackground"			"0"
									"border_default"			"NoBorder"
									"border_armed"				"TLBL_PanelO4_0"
								}
								"Increment"
								{
									"ControlName"				"CExButton"
									"fieldName"					"Increment"
									"xpos"						"16"
									"ypos"						"0"
									"wide"						"16"
									"tall"						"16"
									"proportionaltoparent"		"1"
									"labelText"					">"
									"font"						"iconsSmall"
									"textalignment"				"center"
									"command"					"engine incrementvar sixense_weapon_select_sensitivity 0 360 10"
									"actionsignallevel"			"7"
									"sound_depressed"			"UI/buttonclick.wav"
									"sound_released"			"UI/buttonclickrelease.wav"
									"paintbackground"			"0"
									"border_default"			"NoBorder"
									"border_armed"				"TRBR_PanelO4_0"
								}
							}
							"HueSlider"
							{
								"ControlName"				"CCvarSlider"
								"fieldName"					"HueSlider"
								"xpos"						"-7"
								"ypos"						"0"
								"wide"						"f10"
								"tall"						"20"
								"proportionaltoparent"		"1"
								"cvar_name"					"sixense_weapon_select_sensitivity"
								"minvalue"					"0"
								"maxvalue"					"360"
								"pin_to_sibling"			"Title"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
							}
							"HueSliderImage"
							{
								"ControlName"				"CTFImagePanel"
								"fieldName"					"HueSliderImage"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"f14"
								"tall"						"3"
								"visible"					"1"
								"enabled"					"1"
								"proportionaltoparent"		"1"
								"image"						"replay/thumbnails/misc/hue_slider"
								"scaleImage"				"1"
								"pin_to_sibling"			"HueSlider"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
							}
						}
						"ApplySelection"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"ApplySelection"
							"xpos"						"0"
							"ypos"						"5"
							"wide"						"f10"
							"tall"						"340"
							"proportionaltoparent"		"1"
							"border"					"TLTRBLBR_PanelO2_0"
							"pin_to_sibling"			"ColorSelection"
							"pin_corner_to_sibling"		"PIN_TOPLEFT"
							"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
							"Title"
							{
								"ControlName"					"CExLabel"
								"fieldName"						"Title"
								"xpos"							"0"
								"ypos"							"0"
								"wide"							"f0"
								"tall"							"20"
								"proportionaltoparent"			"1"
								"font"							"regular14"
								"labelText"						"WHAT TO APPLY TO?"
								"textAlignment"					"west"
								"textinsetx"					"5"
								"use_proportional_insets"		"1"
								"border"						"TLTR_PanelO1_0"
							}
							"Buttons"
							{
								"ControlName"				"EditablePanel"
								"fieldName"					"Buttons"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"f0"
								"tall"						"315"
								"proportionaltoparent"		"1"
								"pin_to_sibling"			"Title"
								"pin_corner_to_sibling"		"PIN_TOPLEFT"
								"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
								"General"
								{
									"ControlName"				"EditablePanel"
									"fieldName"					"General"
									"xpos"						"5"
									"ypos"						"5"
									"wide"						"f10"
									"tall"						"60"
									"proportionaltoparent"		"1"
									"border"					"TLTRBLBR_PanelO1_0"
									"Title"
									{
										"ControlName"					"CExLabel"
										"fieldName"						"Title"
										"xpos"							"0"
										"ypos"							"0"
										"wide"							"f0"
										"tall"							"15"
										"proportionaltoparent"			"1"
										"font"							"regular14"
										"labelText"						"GENERAL"
										"textAlignment"					"west"
										"fgcolor_override"				"Text4"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"border"						"NoBorder"
									}
									"AccentMain"
									{
										"ControlName"					"CExButton"
										"fieldName"						"AccentMain"
										"xpos"							"0"
										"ypos"							"15"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Accent Color"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_AccentMain; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"Positive"
									{
										"ControlName"					"CExButton"
										"fieldName"						"Positive"
										"xpos"							"0"
										"ypos"							"25"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Positive Color"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_Positive; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"Warning"
									{
										"ControlName"					"CExButton"
										"fieldName"						"Warning"
										"xpos"							"0"
										"ypos"							"35"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Warning Color"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_Warning; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"Negative"
									{
										"ControlName"					"CExButton"
										"fieldName"						"Negative"
										"xpos"							"0"
										"ypos"							"45"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Negative Color"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_Negative; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
								}
								"Combat"
								{
									"ControlName"				"EditablePanel"
									"fieldName"					"Combat"
									"xpos"						"5"
									"ypos"						"70"
									"wide"						"f10"
									"tall"						"40"
									"proportionaltoparent"		"1"
									"border"					"TLTRBLBR_PanelO1_0"
									"Title"
									{
										"ControlName"					"CExLabel"
										"fieldName"						"Title"
										"xpos"							"0"
										"ypos"							"0"
										"wide"							"f0"
										"tall"							"15"
										"proportionaltoparent"			"1"
										"font"							"regular14"
										"labelText"						"COMBAT"
										"textAlignment"					"west"
										"fgcolor_override"				"Text4"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"border"						"NoBorder"
									}
									"HealNumbers"
									{
										"ControlName"					"CExButton"
										"fieldName"						"HealNumbers"
										"xpos"							"0"
										"ypos"							"15"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Healing Numbers"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_HealNumbers; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"DamageNumbers"
									{
										"ControlName"					"CExButton"
										"fieldName"						"DamageNumbers"
										"xpos"							"0"
										"ypos"							"25"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Damage Numbers"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_DamageNumbers; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
								}
								"Health"
								{
									"ControlName"				"EditablePanel"
									"fieldName"					"Health"
									"xpos"						"5"
									"ypos"						"115"
									"wide"						"f10"
									"tall"						"50"
									"proportionaltoparent"		"1"
									"border"					"TLTRBLBR_PanelO1_0"
									"Title"
									{
										"ControlName"					"CExLabel"
										"fieldName"						"Title"
										"xpos"							"0"
										"ypos"							"0"
										"wide"							"f0"
										"tall"							"15"
										"proportionaltoparent"			"1"
										"font"							"regular14"
										"labelText"						"HEALTH"
										"textAlignment"					"west"
										"fgcolor_override"				"Text4"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"border"						"NoBorder"
									}
									"HealthNormal"
									{
										"ControlName"					"CExButton"
										"fieldName"						"HealthNormal"
										"xpos"							"0"
										"ypos"							"15"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Normal"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_HealthNormal; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"HealthBuff"
									{
										"ControlName"					"CExButton"
										"fieldName"						"HealthBuff"
										"xpos"							"0"
										"ypos"							"25"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Overheal"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_HealthBuff; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"HealthHurt"
									{
										"ControlName"					"CExButton"
										"fieldName"						"HealthHurt"
										"xpos"							"0"
										"ypos"							"35"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Hurt"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_HealthHurt; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
								}
								"Ammo"
								{
									"ControlName"				"EditablePanel"
									"fieldName"					"Ammo"
									"xpos"						"5"
									"ypos"						"170"
									"wide"						"f10"
									"tall"						"80"
									"proportionaltoparent"		"1"
									"border"					"TLTRBLBR_PanelO1_0"
									"Title"
									{
										"ControlName"					"CExLabel"
										"fieldName"						"Title"
										"xpos"							"0"
										"ypos"							"0"
										"wide"							"f0"
										"tall"							"15"
										"proportionaltoparent"			"1"
										"font"							"regular14"
										"labelText"						"AMMO"
										"textAlignment"					"west"
										"fgcolor_override"				"Text4"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"border"						"NoBorder"
									}
									"AmmoClip"
									{
										"ControlName"					"CExButton"
										"fieldName"						"AmmoClip"
										"xpos"							"0"
										"ypos"							"15"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Ammo in Clip"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_AmmoClip; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"AmmoReserve"
									{
										"ControlName"					"CExButton"
										"fieldName"						"AmmoReserve"
										"xpos"							"0"
										"ypos"							"25"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Ammo in Reserve"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_AmmoReserve; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"AmmoNoclip"
									{
										"ControlName"					"CExButton"
										"fieldName"						"AmmoNoclip"
										"xpos"							"0"
										"ypos"							"35"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Ammo not in Clip"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_AmmoNoclip; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"AmmoClipLow"
									{
										"ControlName"					"CExButton"
										"fieldName"						"AmmoClipLow"
										"xpos"							"0"
										"ypos"							"45"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Low Ammo in Clip"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_AmmoClipLow; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"AmmoReserveLow"
									{
										"ControlName"					"CExButton"
										"fieldName"						"AmmoReserveLow"
										"xpos"							"0"
										"ypos"							"55"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Low Ammo in Reserve"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_AmmoReserveLow; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"AmmoNoclipLow"
									{
										"ControlName"					"CExButton"
										"fieldName"						"AmmoNoclipLow"
										"xpos"							"0"
										"ypos"							"65"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Low Ammo not in Clip"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_AmmoNoclipLow; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
								}
								"Medic"
								{
									"ControlName"				"EditablePanel"
									"fieldName"					"Medic"
									"xpos"						"5"
									"ypos"						"255"
									"wide"						"f10"
									"tall"						"40"
									"proportionaltoparent"		"1"
									"border"					"TLTRBLBR_PanelO1_0"
									"Title"
									{
										"ControlName"					"CExLabel"
										"fieldName"						"Title"
										"xpos"							"0"
										"ypos"							"0"
										"wide"							"f0"
										"tall"							"15"
										"proportionaltoparent"			"1"
										"font"							"regular14"
										"labelText"						"MEDIC"
										"textAlignment"					"west"
										"fgcolor_override"				"Text4"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"border"						"NoBorder"
									}
									"Ubercharge"
									{
										"ControlName"					"CExButton"
										"fieldName"						"Ubercharge"
										"xpos"							"0"
										"ypos"							"15"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Übercharge"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_Ubercharge; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
									"UberchargeFull"
									{
										"ControlName"					"CExButton"
										"fieldName"						"UberchargeFull"
										"xpos"							"0"
										"ypos"							"25"
										"wide"							"f0"
										"tall"							"10"
										"proportionaltoparent"			"1"
										"labelText"						"Übercharge Full"
										"font"							"regular12"
										"textAlignment"					"west"
										"textinsetx"					"5"
										"use_proportional_insets"		"1"
										"command"						"engine ih_outcolor; echo IH_APPLYCOLOR_UberchargeFull; ih_printcolor; ih_incolor"
										"actionsignallevel"				"8"
										"sound_depressed"				"UI/buttonclick.wav"
										"sound_released"				"UI/buttonclickrelease.wav"
										"paintbackground"				"0"
										"defaultfgcolor_override"		"Text1"
										"armedfgcolor_override"			"Text0"
									}
								}
								"Reset"
								{
									"ControlName"				"EditablePanel"
									"fieldName"					"Reset"
									"xpos"						"5"
									"ypos"						"300"
									"wide"						"f10"
									"tall"						"15"
									"proportionaltoparent"		"1"
									"border"					"TLTRBLBR_PanelO1_0"
									"Button"
									{
										"ControlName"				"URLLabel"
										"fieldName"					"Button"
										"xpos"						"0"
										"ypos"						"0"
										"wide"						"f0"
										"tall"						"f0"
										"proportionaltoparent"		"1"
										"font"						"regular14"
										"textAlignment"				"center"
										"labelText"					"RESET"
										"urltext"					"tf\custom\insomniaHUD\customization\dev\reset_colors.bat"
									}
									"Icon"
									{
										"ControlName"				"CExLabel"
										"fieldName"					"Icon"
										"xpos"						"0"
										"ypos"						"0"
										"wide"						"15"
										"tall"						"f0"
										"proportionaltoparent"		"1"
										"font"						"iconsSmall"
										"textAlignment"				"center"
										"labelText"					"r"
										"mouseinputenabled"			"0"
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
