"Resource/UI/MainMenuOverride.res"
{
	"MainMenuOverride"
	{
		"CustomizationMenu"
		{
			"MainPanel"
			{
				"SectionContainer"
				{
					"Health"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"Health"
						"xpos"						"420"
						"ypos"						"290"
						"wide"						"210"
						"tall"						"65"
						"proportionaltoparent"		"1"
						"border"					"FLAT_Black_3"
						"Title"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Title"
							"xpos"						"0"
							"ypos"						"0"
							"wide"						"f0"
							"tall"						"20"
							"proportionaltoparent"		"1"
							"font"						"regular14"
							"labelText"					"Health Font Size"
							"fgcolor"					"TextT4"
							"textAlignment"				"center"
							"border"					"NoBorder"
						}
						"Buttons"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"Buttons"
							"xpos"						"5"
							"ypos"						"20"
							"wide"						"f10"
							"tall"						"f25"
							"proportionaltoparent"		"1"
							"border"					"FLAT_Black_4"
							"Small"
							{
								"ControlName"				"CExButton"
								"fieldName"					"Small"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"f0"
								"proportionaltoparent"		"1"
								"labelText"					"Small"
								"textAlignment"				"center"
								"font"						"regular14"
								"paintbackground"			"0"
								"command"					"engine ih_health_small"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
							}
							"Medium"
							{
								"ControlName"				"CExButton"
								"fieldName"					"Medium"
								"xpos"						"60"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"f0"
								"proportionaltoparent"		"1"
								"labelText"					"Medium"
								"textAlignment"				"center"
								"font"						"regular14"
								"paintbackground"			"0"
								"command"					"engine ih_health_medium"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
							}
							"Large"
							{
								"ControlName"				"CExButton"
								"fieldName"					"Large"
								"xpos"						"120"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"f0"
								"proportionaltoparent"		"1"
								"labelText"					"Large"
								"textAlignment"				"center"
								"font"						"regular14"
								"paintbackground"			"0"
								"command"					"engine ih_health_large"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
							}
							"Reset"
							{
								"ControlName"				"CExButton"
								"fieldName"					"Reset"
								"xpos"						"180"
								"ypos"						"0"
								"wide"						"20"
								"tall"						"f0"
								"proportionaltoparent"		"1"
								"labelText"					"r"
								"textAlignment"				"center"
								"font"						"iconsSmall"
								"paintbackground"			"0"
								"command"					"engine ih_health_clear; ih_reloadscheme"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
							}
						}
					}
					"Ammo"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"Ammo"
						"xpos"						"420"
						"ypos"						"355"
						"wide"						"210"
						"tall"						"65"
						"proportionaltoparent"		"1"
						"border"					"FLAT_Black_3"
						"Title"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Title"
							"xpos"						"0"
							"ypos"						"0"
							"wide"						"f0"
							"tall"						"20"
							"proportionaltoparent"		"1"
							"font"						"regular14"
							"labelText"					"Ammo Font Size"
							"fgcolor"					"TextT4"
							"textAlignment"				"center"
							"border"					"NoBorder"
						}
						"Buttons"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"Buttons"
							"xpos"						"5"
							"ypos"						"20"
							"wide"						"f10"
							"tall"						"f25"
							"proportionaltoparent"		"1"
							"border"					"FLAT_Black_4"
							"Small"
							{
								"ControlName"				"CExButton"
								"fieldName"					"Small"
								"xpos"						"0"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"f0"
								"proportionaltoparent"		"1"
								"labelText"					"Small"
								"textAlignment"				"center"
								"font"						"regular14"
								"paintbackground"			"0"
								"command"					"engine ih_ammo_small"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
							}
							"Medium"
							{
								"ControlName"				"CExButton"
								"fieldName"					"Medium"
								"xpos"						"60"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"f0"
								"proportionaltoparent"		"1"
								"labelText"					"Medium"
								"textAlignment"				"center"
								"font"						"regular14"
								"paintbackground"			"0"
								"command"					"engine ih_ammo_medium"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
							}
							"Large"
							{
								"ControlName"				"CExButton"
								"fieldName"					"Large"
								"xpos"						"120"
								"ypos"						"0"
								"wide"						"60"
								"tall"						"f0"
								"proportionaltoparent"		"1"
								"labelText"					"Large"
								"textAlignment"				"center"
								"font"						"regular14"
								"paintbackground"			"0"
								"command"					"engine ih_ammo_large"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
							}
							"Reset"
							{
								"ControlName"				"CExButton"
								"fieldName"					"Reset"
								"xpos"						"180"
								"ypos"						"0"
								"wide"						"20"
								"tall"						"f0"
								"proportionaltoparent"		"1"
								"labelText"					"r"
								"textAlignment"				"center"
								"font"						"iconsSmall"
								"paintbackground"			"0"
								"command"					"engine ih_ammo_clear; ih_reloadscheme"
								"actionsignallevel"			"6"
								"sound_depressed"			"UI/buttonclick.wav"
								"sound_released"			"UI/buttonclickrelease.wav"
								"border_default"			"FLAT_Black_3"
								"border_armed"				"FLAT_Black_2"
							}
						}
					}
				}
			}
		}
	}
}
